/**
 * memory.test.ts — plan 454 §6.1 acceptance for ComputerUseMemory.
 *
 * Coverage:
 *   - parseMemory / serializeMemory round trip
 *   - read / append / write / exists
 *   - sliceForApp: case-insensitive substring match + token budget
 *     truncation
 *   - estTokens heuristic
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  ComputerUseMemory,
  parseMemory,
  serializeMemory,
  sliceForApp,
  estimateTokens,
  DEFAULT_SLICE_TOKEN_BUDGET,
  type MemoryEntry,
} from '../memory/index.js';

describe('parseMemory / serializeMemory — round trip', () => {
  it('parses a canonical memory.md body', () => {
    const body = `# Computer Use Memory

> Auto-generated by Computer Use Mode.

Last updated: 2026-08-28T00:00:00.000Z

## VS Code

- Cmd+K Cmd+S opens keyboard shortcuts
- File > Open Recent > (Empty) clears history

## Chrome

- Cmd+L focuses the address bar
`;
    const entries = parseMemory(body);
    expect(entries.length).toBe(3);
    expect(entries[0]).toEqual({
      app: 'VS Code',
      note: 'Cmd+K Cmd+S opens keyboard shortcuts',
    });
    expect(entries[2]?.app).toBe('Chrome');
  });

  it('survives round trip with timestamp metadata', () => {
    const entries: MemoryEntry[] = [
      { app: 'VS Code', note: 'Cmd+K Cmd+S opens keyboard shortcuts', ts: '2026-08-28T00:00:00.000Z' },
      { app: 'Chrome', note: 'Cmd+L focuses the address bar' },
    ];
    const text = serializeMemory(entries, () => new Date('2026-08-28T12:00:00Z'));
    const parsed = parseMemory(text);
    expect(parsed.length).toBe(2);
    // Section order is alphabetical: Chrome first (no ts), VS Code second (ts preserved).
    expect(parsed[0]?.app).toBe('Chrome');
    expect(parsed[0]?.ts).toBeUndefined();
    expect(parsed[1]?.app).toBe('VS Code');
    expect(parsed[1]?.ts).toBe('2026-08-28T00:00:00.000Z');
  });

  it('tolerates extra blank lines and unknown top-level lines', () => {
    const body = `# header

random prose that should be ignored

## Foo

- entry one

- entry two

`;
    const entries = parseMemory(body);
    expect(entries.length).toBe(2);
    expect(entries.every((e) => e.app === 'Foo')).toBe(true);
  });
});

describe('sliceForApp', () => {
  const entries: MemoryEntry[] = [
    { app: 'VS Code', note: 'Cmd+K Cmd+S opens keyboard shortcuts', ts: '2026-08-28T00:00:00Z' },
    { app: 'VS Code', note: 'Ctrl+` toggles terminal', ts: '2026-08-28T00:01:00Z' },
    { app: 'VS Code', note: 'File > Open Recent > (Empty) clears history', ts: '2026-08-28T00:02:00Z' },
    { app: 'Chrome', note: 'Cmd+L focuses address bar', ts: '2026-08-28T00:03:00Z' },
  ];

  it('matches case-insensitive substring on app', () => {
    const s = sliceForApp(entries, 'vs code');
    expect(s.entries.length).toBe(3);
    expect(s.truncated).toBe(false);
  });

  it('matches notes that lead with the app name', () => {
    const custom: MemoryEntry[] = [
      { app: 'Other', note: 'VS Code: open settings.json via Cmd+,', ts: '2026-01-01T00:00:00Z' },
    ];
    const s = sliceForApp(custom, 'VS Code');
    expect(s.entries.length).toBe(1);
  });

  it('truncates to token budget when entries exceed it', () => {
    const big: MemoryEntry[] = [];
    for (let i = 0; i < 50; i++) {
      big.push({
        app: 'BigApp',
        note: 'a'.repeat(200) + ` #${i}`,
        ts: new Date(2026, 0, 1, 0, i).toISOString(),
      });
    }
    const s = sliceForApp(big, 'BigApp', 100);
    expect(s.truncated).toBe(true);
    expect(s.entries.length).toBeLessThan(50);
    expect(s.tokenEstimate).toBeLessThanOrEqual(100);
  });

  it('returns empty slice for unknown app', () => {
    const s = sliceForApp(entries, 'Photoshop');
    expect(s.entries).toEqual([]);
    expect(s.text).toMatch(/no memory entries/);
    expect(s.truncated).toBe(false);
  });

  it('rendered text starts with the app heading', () => {
    const s = sliceForApp(entries, 'VS Code');
    expect(s.text.startsWith('# VS Code')).toBe(true);
  });
});

describe('estimateTokens', () => {
  it('uses chars/4 heuristic', () => {
    expect(estimateTokens('')).toBe(0);
    expect(estimateTokens('abcd')).toBe(1);
    expect(estimateTokens('abcde')).toBe(2);
  });
});

describe('ComputerUseMemory — file I/O', () => {
  let tempDir: string;
  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'duya-cu-mem-'));
  });
  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  it('returns empty list when file does not exist', async () => {
    const mem = new ComputerUseMemory({ filePath: join(tempDir, 'missing.md') });
    expect(mem.exists()).toBe(false);
    expect(await mem.read()).toEqual([]);
  });

  it('appends a single entry, creates the file', async () => {
    const file = join(tempDir, 'memory.md');
    const mem = new ComputerUseMemory({ filePath: file, now: () => new Date('2026-08-28T12:00:00Z') });
    await mem.append({ app: 'VS Code', note: 'Cmd+K Cmd+S opens keyboard shortcuts' });
    expect(mem.exists()).toBe(true);
    const content = await readFile(file, 'utf-8');
    expect(content).toContain('# Computer Use Memory');
    expect(content).toContain('## VS Code');
    expect(content).toContain('- Cmd+K Cmd+S opens keyboard shortcuts');
    expect(content).toContain('2026-08-28T12:00:00.000Z');
  });

  it('appends multiple entries grouped under the same section', async () => {
    const file = join(tempDir, 'memory.md');
    const mem = new ComputerUseMemory({ filePath: file });
    await mem.append({ app: 'VS Code', note: 'note 1' });
    await mem.append({ app: 'VS Code', note: 'note 2' });
    const entries = await mem.read();
    expect(entries.length).toBe(2);
    expect(entries.every((e) => e.app === 'VS Code')).toBe(true);
  });

  it('creates new sections for distinct apps', async () => {
    const file = join(tempDir, 'memory.md');
    const mem = new ComputerUseMemory({ filePath: file });
    await mem.append({ app: 'VS Code', note: 'a' });
    await mem.append({ app: 'Chrome', note: 'b' });
    const content = await readFile(file, 'utf-8');
    expect(content).toContain('## VS Code');
    expect(content).toContain('## Chrome');
  });

  it('sliceForApp returns matching entries with token-budgeted text', async () => {
    const file = join(tempDir, 'memory.md');
    const mem = new ComputerUseMemory({ filePath: file });
    await mem.append({ app: 'VS Code', note: 'note 1' });
    await mem.append({ app: 'Chrome', note: 'note 2' });
    const slice = await mem.sliceForApp('vs code');
    expect(slice.entries.length).toBe(1);
    // Slice echoes the requested app name (lowercase); we use case-insensitive
    // substring matching, so the slice header is the search string.
    expect(slice.text).toContain('# vs code');
    expect(slice.text).toContain('note 1');
  });

  it('write replaces all entries atomically', async () => {
    const file = join(tempDir, 'memory.md');
    const mem = new ComputerUseMemory({ filePath: file });
    await mem.append({ app: 'VS Code', note: 'old' });
    await mem.write([{ app: 'Foo', note: 'fresh', ts: '2026-01-01T00:00:00Z' }]);
    const entries = await mem.read();
    expect(entries.length).toBe(1);
    expect(entries[0]?.app).toBe('Foo');
  });

  it('exposes DEFAULT_SLICE_TOKEN_BUDGET for callers', () => {
    expect(DEFAULT_SLICE_TOKEN_BUDGET).toBe(500);
  });
});