/**
 * bot-emoji.ts — curated emoji set for the bot avatar picker (combined
 * emoji + background-color selector, Plan 483 P2.1c identity view).
 *
 * A small hand-curated set (mirroring the Notion page-icon grid) instead of
 * the full Unicode table: keeps the bundle small, renders the same on any
 * platform font stack, and lets each entry carry search keywords.
 */

import type { TranslationKey } from "@/i18n";

export interface BotEmoji {
  /** The rendered emoji character. */
  char: string;
  /** Search keywords: English + Chinese + shortcuts. */
  keywords: string;
}

export interface BotEmojiCategory {
  id: string;
  /** Nav tab glyph shown in the category rail. */
  nav: string;
  /** i18n key for the category label / search scope. */
  labelKey: TranslationKey;
  emojis: BotEmoji[];
}

export const BOT_EMOJI_CATEGORIES: readonly BotEmojiCategory[] = [
  {
    id: "people",
    nav: "😊",
    labelKey: "bot.avatarPicker.categories.people",
    emojis: [
      { char: "😀", keywords: "grinning smile face happy" },
      { char: "😃", keywords: "smiley smile happy" },
      { char: "😄", keywords: "smile grin happy laugh" },
      { char: "😁", keywords: "grin laugh joy" },
      { char: "😆", keywords: "laughing face rofl laugh happy" },
      { char: "😅", keywords: "sweat smile relief awkward" },
      { char: "🤣", keywords: "rofl laughter lol crying" },
      { char: "😂", keywords: "joy cry laugh tears" },
      { char: "🙂", keywords: "slight smile calm" },
      { char: "🙃", keywords: "upside down silly" },
      { char: "😉", keywords: "wink flirt cheeky" },
      { char: "😊", keywords: "blush smile shy happy" },
      { char: "😇", keywords: "innocent halo angel" },
      { char: "🥰", keywords: "love smile hearts adore" },
      { char: "😍", keywords: "in love heart eyes crush" },
      { char: "🤩", keywords: "star struck excited amazed" },
      { char: "😘", keywords: "kiss blow fly kiss love" },
      { char: "😗", keywords: "kissing face" },
      { char: "☺️", keywords: "relaxed smile soft" },
      { char: "😚", keywords: "kiss shy closed eyes" },
      { char: "😙", keywords: "kiss smile whistling" },
      { char: "😋", keywords: "yum yummy tasty lick" },
      { char: "😛", keywords: "tongue cheeky playful" },
      { char: "😜", keywords: "winking tongue silly crazy" },
      { char: "🤪", keywords: "zany crazy goofy" },
      { char: "😝", keywords: "squinting tongue playful" },
      { char: "🤗", keywords: "hug smiling hands" },
      { char: "🤭", keywords: "shush giggle hand mouth" },
      { char: "🤫", keywords: "shush quiet whisper" },
      { char: "🤔", keywords: "thinking hmm pondering" },
      { char: "🤨", keywords: "raised eyebrow skeptical" },
      { char: "😐", keywords: "neutral straight face" },
      { char: "😑", keywords: "expressionless bored" },
      { char: "😶", keywords: "no mouth speechless" },
      { char: "😏", keywords: "smirk smug confident" },
      { char: "😒", keywords: "unamused unimpressed" },
      { char: "🙄", keywords: "rolling eyes annoyed" },
      { char: "😬", keywords: "grimace awkward wince" },
      { char: "🤥", keywords: "lying liar pinocchio" },
      { char: "😌", keywords: "relieved calm relaxed" },
      { char: "😔", keywords: "pensive sad dejected" },
      { char: "😪", keywords: "sleepy tired drowsy" },
      { char: "🤤", keywords: "drooling dreaming" },
      { char: "😴", keywords: "sleeping asleep zzz" },
      { char: "😷", keywords: "sick mask face mask" },
      { char: "🤒", keywords: "fever thermometer ill" },
      { char: "🤕", keywords: "injured bandage hurt" },
      { char: "🤢", keywords: "nauseated disgust vomit" },
      { char: "🤮", keywords: "vomiting sick puke" },
      { char: "🤧", keywords: "sneezing sneeze" },
      { char: "🥵", keywords: "hot overheat heat" },
      { char: "🥶", keywords: "cold freezing ice" },
      { char: "🥴", keywords: "woozy dizzy dazed" },
      { char: "😵", keywords: "dizzy confused spinning" },
      { char: "🤯", keywords: "mind blown explosion head" },
      { char: "🤠", keywords: "cowboy hat western" },
      { char: "🥳", keywords: "party celebrating congratulations" },
      { char: "😎", keywords: "cool sunglasses boss" },
      { char: "🤓", keywords: "nerd geek glasses" },
      { char: "🧐", keywords: "monocle detective inspect" },
      { char: "😕", keywords: "confused puzzled" },
      { char: "😟", keywords: "worried worried concern" },
      { char: "🙁", keywords: "slightly frowning sad" },
      { char: "😮", keywords: "surprised shocked open mouth" },
      { char: "😯", keywords: "hushed speechless surprised" },
      { char: "😲", keywords: "astonished amazed shocked" },
      { char: "😳", keywords: "flushed embarrassed blush" },
      { char: "🥺", keywords: "pleading puppy eyes begging" },
      { char: "😢", keywords: "crying tear sad" },
      { char: "😭", keywords: "sobbing crying loud tear" },
      { char: "😤", keywords: "triumph frustrated steam angry" },
      { char: "😠", keywords: "angry mad upset" },
      { char: "😡", keywords: "pouting rage furious red face" },
      { char: "🤬", keywords: "cursing swear angry symbols" },
      { char: "😈", keywords: "smiling devil mischievous" },
      { char: "👿", keywords: "angry devil evil" },
      { char: "💀", keywords: "skull death danger" },
      { char: "☠️", keywords: "skull crossbones pirate" },
      { char: "💩", keywords: "poop pile crap" },
      { char: "🤡", keywords: "clown silly joke" },
      { char: "👻", keywords: "ghost spooky halloween" },
      { char: "👽", keywords: "alien ufo space" },
      { char: "🤖", keywords: "robot bot machine" },
      { char: "🎃", keywords: "pumpkin halloween" },
      { char: "😺", keywords: "happy cat" },
      { char: "😸", keywords: "grinning cat" },
      { char: "😻", keywords: "heart eyes cat" },
      { char: "😼", keywords: "smirk cat" },
      { char: "🙈", keywords: "see no evil monkey" },
      { char: "🙉", keywords: "hear no evil monkey" },
      { char: "🙊", keywords: "speak no evil monkey" },
    ],
  },
  {
    id: "hands",
    nav: "👋",
    labelKey: "bot.avatarPicker.categories.hands",
    emojis: [
      { char: "👋", keywords: "wave hello hi goodbye" },
      { char: "🤚", keywords: "raised back hand hand" },
      { char: "✋", keywords: "hand raised stop high five" },
      { char: "🖖", keywords: "vulcan salute spock" },
      { char: "👌", keywords: "ok okay perfect hand" },
      { char: "🤌", keywords: "pinched fingers chef" },
      { char: "🤏", keywords: "pinching hand tiny" },
      { char: "🤞", keywords: "fingers crossed luck" },
      { char: "🤟", keywords: "i love you hand" },
      { char: "🤘", keywords: "rock on horns metal" },
      { char: "🤙", keywords: "call me shaka" },
      { char: "👈", keywords: "pointing left" },
      { char: "👉", keywords: "pointing right" },
      { char: "👆", keywords: "pointing up" },
      { char: "👇", keywords: "pointing down" },
      { char: "☝️", keywords: "pointing index one" },
      { char: "👍", keywords: "thumbs up yes like good" },
      { char: "👎", keywords: "thumbs down no dislike" },
      { char: "✊", keywords: "fist fist bump" },
      { char: "👊", keywords: "oncoming fist punch" },
      { char: "👏", keywords: "clapping clap applause" },
      { char: "🙌", keywords: "raising hands celebrate hooray" },
      { char: "👐", keywords: "open hands hug" },
      { char: "🤲", keywords: "palms up offering" },
      { char: "🙏", keywords: "pray thanks please folded" },
      { char: "✍️", keywords: "writing hand" },
      { char: "💅", keywords: "nail polish fancy" },
      { char: "🤳", keywords: "selfie camera" },
      { char: "💪", keywords: "muscle strong flex arm" },
      { char: "🦾", keywords: "mechanical arm prosthetic" },
      { char: "🦿", keywords: "mechanical leg prosthetic" },
      { char: "🦵", keywords: "leg kick" },
      { char: "🦶", keywords: "foot" },
      { char: "👂", keywords: "ear listen" },
      { char: "👃", keywords: "nose smell" },
      { char: "🧠", keywords: "brain mind think" },
      { char: "🦷", keywords: "tooth" },
      { char: "👀", keywords: "eyes watch see" },
      { char: "👁️", keywords: "eye see" },
      { char: "👅", keywords: "tongue taste" },
      { char: "👄", keywords: "mouth lips" },
    ],
  },
  {
    id: "nature",
    nav: "🌿",
    labelKey: "bot.avatarPicker.categories.nature",
    emojis: [
      { char: "🐶", keywords: "dog pet puppy" },
      { char: "🐱", keywords: "cat kitty kitten pet" },
      { char: "🐭", keywords: "mouse" },
      { char: "🐹", keywords: "hamster" },
      { char: "🐰", keywords: "rabbit bunny" },
      { char: "🦊", keywords: "fox red" },
      { char: "🐻", keywords: "bear" },
      { char: "🐼", keywords: "panda" },
      { char: "🐨", keywords: "koala" },
      { char: "🐯", keywords: "tiger" },
      { char: "🦁", keywords: "lion king" },
      { char: "🐮", keywords: "cow" },
      { char: "🐷", keywords: "pig" },
      { char: "🐸", keywords: "frog" },
      { char: "🐵", keywords: "monkey" },
      { char: "🐔", keywords: "chicken rooster" },
      { char: "🐧", keywords: "penguin" },
      { char: "🐦", keywords: "bird" },
      { char: "🐤", keywords: "chick baby" },
      { char: "🦆", keywords: "duck" },
      { char: "🦅", keywords: "eagle" },
      { char: "🦉", keywords: "owl" },
      { char: "🦋", keywords: "butterfly" },
      { char: "🐌", keywords: "snail slow" },
      { char: "🐛", keywords: "bug worm" },
      { char: "🐝", keywords: "bee honey" },
      { char: "🐞", keywords: "ladybug beetle" },
      { char: "🦄", keywords: "unicorn magical" },
      { char: "🐙", keywords: "octopus" },
      { char: "🦀", keywords: "crab" },
      { char: "🐢", keywords: "turtle" },
      { char: "🐍", keywords: "snake" },
      { char: "🐳", keywords: "whale" },
      { char: "🐬", keywords: "dolphin" },
      { char: "🐠", keywords: "tropical fish" },
      { char: "🦈", keywords: "shark" },
      { char: "🌵", keywords: "cactus desert" },
      { char: "🌲", keywords: "evergreen tree" },
      { char: "🌳", keywords: "deciduous tree wood" },
      { char: "🌴", keywords: "palm tree tropical beach" },
      { char: "🌿", keywords: "herb leaf green" },
      { char: "🍀", keywords: "clover four leaf luck" },
      { char: "🍁", keywords: "maple leaf autumn fall" },
      { char: "🍂", keywords: "fallen leaf fall" },
      { char: "🌸", keywords: "cherry blossom flower" },
      { char: "🌹", keywords: "rose flower" },
      { char: "🌻", keywords: "sunflower" },
      { char: "🌷", keywords: "tulip" },
      { char: "🌱", keywords: "seedling sprout grow" },
    ],
  },
  {
    id: "food",
    nav: "🍎",
    labelKey: "bot.avatarPicker.categories.food",
    emojis: [
      { char: "🍏", keywords: "green apple fruit" },
      { char: "🍎", keywords: "red apple fruit" },
      { char: "🍊", keywords: "orange clementine fruit" },
      { char: "🍋", keywords: "lemon" },
      { char: "🍌", keywords: "banana" },
      { char: "🍉", keywords: "watermelon" },
      { char: "🍇", keywords: "grapes" },
      { char: "🍓", keywords: "strawberry berry" },
      { char: "🫐", keywords: "blueberries berry" },
      { char: "🍒", keywords: "cherries" },
      { char: "🍑", keywords: "peach" },
      { char: "🥭", keywords: "mango" },
      { char: "🍍", keywords: "pineapple" },
      { char: "🥥", keywords: "coconut" },
      { char: "🥝", keywords: "kiwi" },
      { char: "🍅", keywords: "tomato" },
      { char: "🥑", keywords: "avocado" },
      { char: "🥦", keywords: "broccoli vegetable" },
      { char: "🥬", keywords: "leafy green vegetable" },
      { char: "🥕", keywords: "carrot" },
      { char: "🌽", keywords: "corn maize" },
      { char: "🥔", keywords: "potato" },
      { char: "🍞", keywords: "bread loaf" },
      { char: "🥐", keywords: "croissant" },
      { char: "🥯", keywords: "bagel" },
      { char: "🧀", keywords: "cheese" },
      { char: "🍖", keywords: "meat bone" },
      { char: "🍕", keywords: "pizza" },
      { char: "🍔", keywords: "hamburger burger" },
      { char: "🍟", keywords: "fries french fries" },
      { char: "🌭", keywords: "hot dog" },
      { char: "🍿", keywords: "popcorn" },
      { char: "🧈", keywords: "butter" },
      { char: "🍜", keywords: "noodles ramen" },
      { char: "🍝", keywords: "spaghetti pasta" },
      { char: "🍣", keywords: "sushi" },
      { char: "🍱", keywords: "bento box" },
      { char: "🍤", keywords: "fried shrimp" },
      { char: "🍚", keywords: "cooked rice" },
      { char: "🍰", keywords: "cake shortcake dessert" },
      { char: "🍦", keywords: "ice cream soft" },
      { char: "🍨", keywords: "ice cream bowl dessert" },
      { char: "🍩", keywords: "donut doughnut" },
      { char: "🍪", keywords: "cookie" },
      { char: "🎂", keywords: "birthday cake celebrate" },
      { char: "🧁", keywords: "cupcake" },
      { char: "🍫", keywords: "chocolate" },
      { char: "☕", keywords: "coffee hot drink" },
      { char: "🍵", keywords: "tea green tea" },
      { char: "🥤", keywords: "cup drink soda" },
      { char: "🧋", keywords: "bubble tea boba" },
    ],
  },
  {
    id: "activity",
    nav: "⚽",
    labelKey: "bot.avatarPicker.categories.activity",
    emojis: [
      { char: "⚽", keywords: "soccer football" },
      { char: "🏀", keywords: "basketball" },
      { char: "🏈", keywords: "american football" },
      { char: "⚾", keywords: "baseball" },
      { char: "🎾", keywords: "tennis" },
      { char: "🏐", keywords: "volleyball" },
      { char: "🏉", keywords: "rugby" },
      { char: "🥏", keywords: "frisbee disc" },
      { char: "🎱", keywords: "billiards pool eight ball" },
      { char: "⛳", keywords: "golf flag hole" },
      { char: "🏓", keywords: "ping pong table tennis" },
      { char: "🏸", keywords: "badminton shuttlecock" },
      { char: "🥊", keywords: "boxing glove" },
      { char: "🥋", keywords: "martial arts karate" },
      { char: "⛸️", keywords: "skate ice skating" },
      { char: "🎿", keywords: "ski skiing" },
      { char: "🛷", keywords: "sled sledge" },
      { char: "🏂", keywords: "snowboarder snowboarding" },
      { char: "🏋️", keywords: "weight lifting gym" },
      { char: "🤸", keywords: "cartwheeling gymnast" },
      { char: "🚴", keywords: "bicyclist cycling bike" },
      { char: "🏇", keywords: "horse racing" },
      { char: "🧗", keywords: "climbing rock" },
      { char: "🏄", keywords: "surfing" },
      { char: "🏊", keywords: "swimming swim" },
      { char: "🏹", keywords: "archery bow arrow" },
      { char: "🎮", keywords: "video game controller play" },
      { char: "🎲", keywords: "dice board game" },
      { char: "♟️", keywords: "chess pawn" },
      { char: "🎯", keywords: "dart target bullseye aim" },
      { char: "🎳", keywords: "bowling" },
      { char: "🎤", keywords: "microphone karaoke sing" },
      { char: "🎧", keywords: "headphone music listen" },
      { char: "🎹", keywords: "musical keyboard piano" },
      { char: "🎸", keywords: "guitar" },
      { char: "🥁", keywords: "drum drumstick" },
      { char: "🎬", keywords: "clapper movie film" },
      { char: "🎨", keywords: "art palette paint creative" },
      { char: "🧩", keywords: "puzzle piece" },
      { char: "🎭", keywords: "theater masks acting" },
      { char: "🎪", keywords: "circus tent" },
      { char: "🎈", keywords: "balloon party" },
      { char: "🎉", keywords: "party popper congratulations" },
      { char: "🎊", keywords: "confetti celebration" },
      { char: "🎁", keywords: "gift present wrapped" },
      { char: "🏆", keywords: "trophy winner champion" },
      { char: "🏅", keywords: "medal sports" },
      { char: "🥇", keywords: "gold medal first" },
      { char: "🥈", keywords: "silver medal second" },
      { char: "🥉", keywords: "bronze medal third" },
    ],
  },
  {
    id: "travel",
    nav: "✈️",
    labelKey: "bot.avatarPicker.categories.travel",
    emojis: [
      { char: "✈️", keywords: "airplane plane flight travel" },
      { char: "🚀", keywords: "rocket space launch fast" },
      { char: "🛸", keywords: "flying saucer ufo alien" },
      { char: "🚗", keywords: "car automobile vehicle" },
      { char: "🚕", keywords: "taxi cab taxi" },
      { char: "🚙", keywords: "suv off road car" },
      { char: "🚌", keywords: "bus vehicle" },
      { char: "🚎", keywords: "trolleybus bus" },
      { char: "🏎️", keywords: "racing car f1 speed" },
      { char: "🚓", keywords: "police car" },
      { char: "🚑", keywords: "ambulance medical" },
      { char: "🚁", keywords: "helicopter" },
      { char: "🚂", keywords: "locomotive train engine" },
      { char: "🚄", keywords: "high speed train bullet" },
      { char: "🚅", keywords: "bullet train fast" },
      { char: "🚇", keywords: "metro subway underground" },
      { char: "🚢", keywords: "ship boat cruise" },
      { char: "⛵", keywords: "sailboat sailing" },
      { char: "🛶", keywords: "canoe kayak" },
      { char: "🚲", keywords: "bicycle bike cycle" },
      { char: "🛴", keywords: "kick scooter" },
      { char: "🛵", keywords: "motor scooter" },
      { char: "🏍️", keywords: "motorcycle motorbike" },
      { char: "🚦", keywords: "traffic light" },
      { char: "🗺️", keywords: "world map map" },
      { char: "🧭", keywords: "compass navigate" },
      { char: "⛰️", keywords: "mountain" },
      { char: "🏔️", keywords: "snow capped mountain" },
      { char: "🏖️", keywords: "beach with umbrella" },
      { char: "🏜️", keywords: "desert" },
      { char: "🏝️", keywords: "desert island" },
      { char: "🏙️", keywords: "city skyline urban" },
      { char: "🏯", keywords: "japanese castle" },
      { char: "⛩️", keywords: "shinto shrine" },
      { char: "🏛️", keywords: "classical building" },
      { char: "🗽", keywords: "statue of liberty new york" },
      { char: "🏰", keywords: "castle fairytale" },
      { char: "🎡", keywords: "ferris wheel amusement park" },
      { char: "🎢", keywords: "roller coaster" },
      { char: "🌋", keywords: "volcano eruption" },
      { char: "🗼", keywords: "tokyo tower" },
      { char: "🌉", keywords: "bridge" },
    ],
  },
  {
    id: "objects",
    nav: "💡",
    labelKey: "bot.avatarPicker.categories.objects",
    emojis: [
      { char: "⌚", keywords: "watch time" },
      { char: "📱", keywords: "mobile phone smartphone" },
      { char: "💻", keywords: "laptop notebook computer" },
      { char: "⌨️", keywords: "keyboard" },
      { char: "🖥️", keywords: "desktop computer" },
      { char: "🖨️", keywords: "printer" },
      { char: "🖱️", keywords: "mouse computer" },
      { char: "📷", keywords: "camera photo" },
      { char: "📸", keywords: "camera flash selfie" },
      { char: "🎥", keywords: "video camera movie" },
      { char: "🎞️", keywords: "film frames" },
      { char: "📹", keywords: "video camera vlog" },
      { char: "🔍", keywords: "magnifying glass tilted left search" },
      { char: "🔎", keywords: "magnifying glass tilted right search" },
      { char: "💡", keywords: "light bulb idea" },
      { char: "🔦", keywords: "flashlight torch" },
      { char: "🔋", keywords: "battery power" },
      { char: "🔌", keywords: "plug electric" },
      { char: "📕", keywords: "red book" },
      { char: "📗", keywords: "green book" },
      { char: "📘", keywords: "blue book" },
      { char: "📙", keywords: "orange book" },
      { char: "📓", keywords: "notebook" },
      { char: "📔", keywords: "notebook decorative" },
      { char: "📒", keywords: "ledger notepad" },
      { char: "📚", keywords: "books library" },
      { char: "📖", keywords: "open book reading" },
      { char: "📝", keywords: "memo note pencil write" },
      { char: "✏️", keywords: "pencil write" },
      { char: "✂️", keywords: "scissors cut" },
      { char: "📌", keywords: "pushpin pin" },
      { char: "📍", keywords: "round pushpin location" },
      { char: "✉️", keywords: "envelope email mail" },
      { char: "📧", keywords: "e mail email" },
      { char: "📨", keywords: "incoming envelope" },
      { char: "📩", keywords: "envelope with arrow" },
      { char: "📤", keywords: "outbox tray sent" },
      { char: "📥", keywords: "inbox tray received" },
      { char: "📦", keywords: "package box delivery" },
      { char: "🗑️", keywords: "wastebasket trash delete" },
      { char: "🔒", keywords: "locked padlock security" },
      { char: "🔓", keywords: "unlocked open padlock" },
      { char: "🔑", keywords: "key access lock" },
      { char: "🗝️", keywords: "old key" },
      { char: "🔨", keywords: "hammer tool" },
      { char: "🛠️", keywords: "hammer and wrench tool" },
      { char: "⚙️", keywords: "gear settings engineering" },
      { char: "🧰", keywords: "toolbox kit" },
      { char: "📎", keywords: "paperclip attach" },
      { char: "📏", keywords: "ruler measure" },
      { char: "📐", keywords: "triangular ruler" },
      { char: "🔬", keywords: "microscope science lab" },
      { char: "🔭", keywords: "telescope astronomy" },
      { char: "💎", keywords: "gem diamond jewel" },
    ],
  },
  {
    id: "symbols",
    nav: "💡",
    labelKey: "bot.avatarPicker.categories.symbols",
    emojis: [
      { char: "❤️", keywords: "heart red love" },
      { char: "🧡", keywords: "orange heart love" },
      { char: "💛", keywords: "yellow heart love" },
      { char: "💚", keywords: "green heart love" },
      { char: "💙", keywords: "blue heart love" },
      { char: "💜", keywords: "purple heart love" },
      { char: "🖤", keywords: "black heart love" },
      { char: "🤍", keywords: "white heart love" },
      { char: "💔", keywords: "broken heart sad" },
      { char: "💕", keywords: "two hearts love" },
      { char: "💖", keywords: "sparkling heart love" },
      { char: "💗", keywords: "growing heart love" },
      { char: "💓", keywords: "beating heart love" },
      { char: "💞", keywords: "revolving hearts love" },
      { char: "💫", keywords: "dizzy stars sparkle" },
      { char: "✨", keywords: "sparkles shine magic" },
      { char: "⭐", keywords: "star rating" },
      { char: "🌟", keywords: "glowing star" },
      { char: "⚡", keywords: "high voltage lightning energy" },
      { char: "🔥", keywords: "fire hot burn" },
      { char: "💥", keywords: "collision boom explosion" },
      { char: "💦", keywords: "sweat droplets water" },
      { char: "💨", keywords: "dashing away wind speed" },
      { char: "☀️", keywords: "sun sunny weather" },
      { char: "🌤️", keywords: "sun behind small cloud" },
      { char: "⛅", keywords: "sun behind cloud partly cloudy" },
      { char: "☁️", keywords: "cloud weather" },
      { char: "🌈", keywords: "rainbow colorful" },
      { char: "❄️", keywords: "snowflake winter cold" },
      { char: "☃️", keywords: "snowman winter" },
      { char: "🌪️", keywords: "tornado cyclone" },
      { char: "💧", keywords: "droplet water" },
      { char: "🌊", keywords: "water wave ocean sea" },
      { char: "🌙", keywords: "crescent moon night" },
      { char: "🌕", keywords: "full moon night" },
      { char: "☄️", keywords: "comet space" },
      { char: "💯", keywords: "hundred points perfect" },
      { char: "🔔", keywords: "bell notification" },
      { char: "🔕", keywords: "bell with slash mute" },
      { char: "🎵", keywords: "musical note music sing" },
      { char: "🎶", keywords: "musical notes music" },
      { char: "✅", keywords: "check mark button yes done" },
      { char: "❌", keywords: "cross mark no wrong" },
      { char: "⭕", keywords: "o mark circle" },
      { char: "❗", keywords: "red exclamation important alert" },
      { char: "❓", keywords: "red question mark help" },
      { char: "🚩", keywords: "triangular flag" },
      { char: "🏁", keywords: "chequered flag finish race" },
    ],
  },
  {
    id: "flags",
    nav: "🏳️",
    labelKey: "bot.avatarPicker.categories.flags",
    emojis: [
      { char: "🇺🇸", keywords: "united states usa america flag" },
      { char: "🇬🇧", keywords: "united kingdom uk england flag" },
      { char: "🇨🇳", keywords: "china flag" },
      { char: "🇯🇵", keywords: "japan flag" },
      { char: "🇰🇷", keywords: "south korea korea flag" },
      { char: "🇫🇷", keywords: "france flag" },
      { char: "🇩🇪", keywords: "germany flag" },
      { char: "🇮🇹", keywords: "italy flag" },
      { char: "🇪🇸", keywords: "spain flag" },
      { char: "🇷🇺", keywords: "russia flag" },
      { char: "🇧🇷", keywords: "brazil flag" },
      { char: "🇨🇦", keywords: "canada flag" },
      { char: "🇦🇺", keywords: "australia flag" },
      { char: "🇮🇳", keywords: "india flag" },
      { char: "🇸🇬", keywords: "singapore flag" },
      { char: "🇸🇦", keywords: "saudi arabia flag" },
      { char: "🇦🇪", keywords: "united arab emirates uae flag" },
      { char: "🇳🇱", keywords: "netherlands holland flag" },
      { char: "🇹🇭", keywords: "thailand flag" },
      { char: "🇻🇳", keywords: "vietnam flag" },
      { char: "🇵🇭", keywords: "philippines flag" },
      { char: "🇲🇾", keywords: "malaysia flag" },
      { char: "🇮🇩", keywords: "indonesia flag" },
      { char: "🇳🇿", keywords: "new zealand flag" },
      { char: "🇿🇦", keywords: "south africa flag" },
      { char: "🇲🇽", keywords: "mexico flag" },
      { char: "🇦🇷", keywords: "argentina flag" },
      { char: "🏳️", keywords: "white flag" },
      { char: "🏴", keywords: "black flag" },
      { char: "🏳️‍🌈", keywords: "rainbow flag pride" },
    ],
  },
];

/** Flattened emojis with a category label, used by the picker grid. */
export type BotEmojiEntry = BotEmoji & { categoryId: string };

export const BOT_EMOJIS: readonly BotEmojiEntry[] = BOT_EMOJI_CATEGORIES.flatMap((c) =>
  c.emojis.map((e) => ({ ...e, categoryId: c.id })),
);

/** Find a category by id (fallback: first category). */
export function botEmojiCategoryById(id: string): BotEmojiCategory {
  return BOT_EMOJI_CATEGORIES.find((c) => c.id === id) ?? BOT_EMOJI_CATEGORIES[0];
}

/** Case-insensitive keyword filter used for the search box. */
export function filterBotEmojis(query: string): BotEmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return BOT_EMOJIS.filter((e) => e.keywords.toLowerCase().includes(q));
}