/**
 * src/lib/providers/presets/anthropic.ts
 *
 * Anthropic-protocol presets. These are all `apiFormat: 'anthropic'` and
 * use Bearer / x-api-key auth. They may live behind third-party proxies
 * (GLM, Kimi, MiniMax, Volcengine, Xiaomi, StepFun, OpenRouter-Anthropic,
 *  BigModel, etc.) but share the same wire protocol.
 */

import type { ProviderPreset } from '../types';

const ANTHROPIC_AUTH_FIELDS = [
  { key: 'api_key', label: 'API Key', secret: true, required: true },
];

export const ANTHROPIC_PRESETS: ProviderPreset[] = [
  {
    key: 'anthropic-official',
    name: 'Anthropic',
    description: "Anthropic's official Claude API",
    descriptionZh: 'Anthropic 官方 Claude API',
    category: 'official',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.anthropic.com',
    modelsSource: { type: 'static' },
    defaultModels: [
      'claude-sonnet-4-6',
      'claude-opus-4-7',
      'claude-opus-4-6',
      'claude-haiku-4-5',
    ],
    defaultModelLabels: {
      'claude-sonnet-4-6': 'Claude Sonnet 4.6',
      'claude-opus-4-7': 'Claude Opus 4.7',
      'claude-opus-4-6': 'Claude Opus 4.6',
      'claude-haiku-4-5': 'Claude Haiku 4.5',
    },
    ui: {
      icon: 'anthropic',
      iconColor: '#D4915D',
      websiteUrl: 'https://www.anthropic.com',
      apiKeyUrl: 'https://console.anthropic.com/',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'anthropic-thirdparty',
    name: 'Anthropic Third-party API',
    description: 'Anthropic-compatible API — provide URL and Key',
    descriptionZh: 'Anthropic 兼容第三方 API — 填写地址和密钥',
    category: 'custom',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: '',
    modelsSource: { type: 'static' },
    defaultModels: ['claude-sonnet-4-6', 'claude-opus-4-6', 'claude-haiku-4-5'],
    ui: {
      icon: 'server',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek Anthropic-compatible API — V4 Pro / V4 Flash',
    descriptionZh: 'DeepSeek Anthropic 兼容 API — V4 Pro / V4 Flash',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.deepseek.com/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'deepseek-v4-pro',
      'deepseek-v4-flash',
      'deepseek-chat',
      'deepseek-reasoner',
    ],
    defaultModelLabels: {
      'deepseek-v4-pro': 'DeepSeek V4 Pro',
      'deepseek-v4-flash': 'DeepSeek V4 Flash',
      'deepseek-chat': 'DeepSeek Chat',
      'deepseek-reasoner': 'DeepSeek Reasoner',
    },
    templateValues: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    ui: {
      icon: 'deepseek',
      iconColor: '#1E88E5',
      websiteUrl: 'https://platform.deepseek.com',
      apiKeyUrl: 'https://platform.deepseek.com/api_keys',
      docsUrl: 'https://platform.deepseek.com/docs',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'glm-cn',
    name: 'GLM (CN)',
    description: 'Zhipu GLM Code Plan — China region',
    descriptionZh: '智谱 GLM 编程套餐 — 中国区',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://open.bigmodel.cn/api/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'glm-5.1',
      'glm-5',
      'glm-5-turbo',
      'glm-5v-turbo',
      'glm-4.7',
      'glm-4.5',
      'glm-4.5-flash',
      'glm-4.5-air',
    ],
    defaultModelLabels: {
      'glm-5.1': 'GLM-5.1',
      'glm-5': 'GLM-5',
      'glm-5-turbo': 'GLM-5 Turbo',
      'glm-5v-turbo': 'GLM-5V Turbo',
      'glm-4.7': 'GLM-4.7',
      'glm-4.5': 'GLM-4.5',
      'glm-4.5-flash': 'GLM-4.5 Flash',
      'glm-4.5-air': 'GLM-4.5 Air',
    },
    templateValues: { API_TIMEOUT_MS: '3000000' },
    ui: {
      icon: 'zhipu',
      iconColor: '#0F62FE',
      websiteUrl: 'https://bigmodel.cn',
      apiKeyUrl: 'https://bigmodel.cn/usercenter/proj-mgmt/apikeys',
      docsUrl: 'https://docs.bigmodel.cn/cn/coding-plan/tool/claude',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'glm-global',
    name: 'GLM (Global)',
    description: 'Zhipu GLM Code Plan — Global region',
    descriptionZh: '智谱 GLM 编程套餐 — 国际区',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.z.ai/api/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'glm-5.1',
      'glm-5',
      'glm-5-turbo',
      'glm-5v-turbo',
      'glm-4.7',
      'glm-4.5',
      'glm-4.5-flash',
      'glm-4.5-air',
    ],
    ui: {
      icon: 'zhipu',
      iconColor: '#0F62FE',
      websiteUrl: 'https://z.ai',
      apiKeyUrl: 'https://z.ai/manage-apikey/apikey-list',
      docsUrl: 'https://docs.z.ai/devpack/tool/claude',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'kimi',
    name: 'Kimi',
    description: 'Kimi Coding Plan API',
    descriptionZh: 'Kimi 编程计划 API',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.kimi.com/coding/',
    modelsSource: { type: 'static' },
    defaultModels: [
      'kimi-k2.6',
      'kimi-k2.5',
      'kimi-k2',
      'kimi-k2-thinking',
      'kimi-k2-thinking-turbo',
      'kimi-k2-turbo-preview',
      'kimi-k2-0905-preview',
    ],
    templateValues: { ENABLE_TOOL_SEARCH: 'false' },
    ui: {
      icon: 'kimi',
      iconColor: '#6366F1',
      websiteUrl: 'https://www.kimi.com',
      apiKeyUrl: 'https://www.kimi.com/code/console',
      docsUrl: 'https://www.kimi.com/code/docs/more/third-party-agents.html',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'moonshot',
    name: 'Moonshot',
    description: 'Moonshot AI API',
    descriptionZh: '月之暗面 API',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.moonshot.cn/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'kimi-k2.6',
      'kimi-k2.5',
      'kimi-k2',
      'kimi-k2-thinking',
      'kimi-k2-thinking-turbo',
    ],
    templateValues: { ENABLE_TOOL_SEARCH: 'false' },
    ui: {
      icon: 'moonshot',
      iconColor: '#6366F1',
      websiteUrl: 'https://platform.moonshot.cn',
      apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
      docsUrl: 'https://platform.moonshot.cn/docs/guide/agent-support',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'minimax-cn',
    name: 'MiniMax (CN)',
    description: 'MiniMax Code Plan — China region',
    descriptionZh: 'MiniMax 编程套餐 — 中国区',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.minimaxi.com/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'MiniMax-M3',
      'MiniMax-M2.7',
      'MiniMax-M2.5',
      'MiniMax-M2.1',
      'MiniMax-M2',
    ],
    templateValues: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    ui: {
      icon: 'minimax',
      iconColor: '#FF6B6B',
      websiteUrl: 'https://platform.minimaxi.com',
      apiKeyUrl: 'https://platform.minimaxi.com/user-center/payment/token-plan',
      docsUrl: 'https://platform.minimaxi.com/docs/token-plan/claude-code',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'minimax-global',
    name: 'MiniMax (Global)',
    description: 'MiniMax Code Plan — Global region',
    descriptionZh: 'MiniMax 编程套餐 — 国际区',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.minimax.io/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: [
      'MiniMax-M3',
      'MiniMax-M2.7',
      'MiniMax-M2.5',
      'MiniMax-M2.1',
      'MiniMax-M2',
    ],
    templateValues: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    ui: {
      icon: 'minimax',
      iconColor: '#FF6B6B',
      websiteUrl: 'https://platform.minimax.io',
      apiKeyUrl: 'https://platform.minimax.io/user-center/payment/token-plan',
      docsUrl: 'https://platform.minimax.io/docs/token-plan/opencode',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'volcengine',
    name: 'Volcengine Ark',
    description: 'Volcengine Ark Coding Plan — Doubao, GLM, DeepSeek, Kimi',
    descriptionZh: '字节火山方舟 Coding Plan — 豆包、GLM、DeepSeek、Kimi',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://ark.cn-beijing.volces.com/api/coding',
    modelsSource: { type: 'static' },
    defaultModels: [
      'doubao-1.5-pro-32k',
      'doubao-1.5-lite-32k',
      'doubao-pro-32k',
      'doubao-lite-32k',
      'deepseek-v3-241226',
      'deepseek-r1-250120',
      'glm-4-9b-chat',
      'glm-4-flash',
      'kimi-k2.5',
    ],
    ui: {
      icon: 'volcengine',
      iconColor: '#FF6A00',
      websiteUrl: 'https://www.volcengine.com',
      apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement',
      docsUrl: 'https://www.volcengine.com/docs/82379/1928262',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'stepfun',
    name: 'StepFun Step Plan',
    description: 'StepFun Step Plan — Fast reasoning and coding',
    descriptionZh: '阶跃星辰 Step Plan — 快速推理与编程',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.stepfun.ai/step_plan/v1',
    modelsSource: { type: 'static' },
    defaultModels: ['step-3.5-flash', 'step-3.5-flash-2603'],
    templateValues: { API_TIMEOUT_MS: '3000000' },
    ui: {
      icon: 'stepfun',
      websiteUrl: 'https://platform.stepfun.com',
      apiKeyUrl: 'https://platform.stepfun.com/api',
      docsUrl: 'https://platform.stepfun.com/docs',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'xiaomi-mimo',
    name: 'Xiaomi MiMo',
    description: 'Xiaomi MiMo Pay-as-you-go API — MiMo-V2.5-Pro',
    descriptionZh: '小米 MiMo 按量付费 — MiMo-V2.5-Pro',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://api.xiaomimimo.com/anthropic',
    modelsSource: { type: 'static' },
    defaultModels: ['MiMo-V2.5-Pro'],
    ui: {
      icon: 'xiaomi',
      websiteUrl: 'https://api.xiaomimimo.com',
    },
    legacyProtocol: 'anthropic',
  },
  {
    key: 'bailian',
    name: 'Alibaba Bailian',
    description: 'Alibaba Bailian — Model Studio API',
    descriptionZh: '阿里云百炼 — 模型工作室 API',
    category: 'aggregator',
    apiFormat: 'anthropic',
    authFields: ANTHROPIC_AUTH_FIELDS,
    defaultEndpoint: 'https://dashscope.aliyuncs.com/api',
    modelsSource: { type: 'static' },
    defaultModels: ['qwen3-max', 'qwen3-coder-plus', 'qwen3-vl-plus'],
    ui: {
      icon: 'bailian',
      iconColor: '#FF6A00',
      websiteUrl: 'https://bailian.console.aliyun.com',
    },
    legacyProtocol: 'anthropic',
  },
];
