/**
 * memory/index.ts — ComputerUseMemory (plan 454 §5 Task A).
 *
 * Persists per-app UI knowledge to `~/.duya/computer-use/memory.md`
 * so future agent runs (and sub-agents in Phase 3 Task B) can reuse
 * shortcut / structure knowledge without rediscovering it.
 *
 * File format (Markdown, intentionally human-editable):
 *
 *   # Computer Use Memory
 *
 *   Last updated: 2026-08-28T12:34:56.000Z
 *
 *   ## VS Code
 *
 *   - Cmd+K Cmd+S opens keyboard shortcuts
 *   - File > Open Recent > (Empty) clears history
 *   - `Ctrl+\`` toggles the integrated terminal
 *
 *   ## Chrome
 *
 *   - Cmd+L focuses the address bar
 *   - Cmd+Shift+T reopens the last closed tab
 *
 * The module is platform-agnostic and Node-only. The Electron main
 * process owns the file path; tests inject a custom path.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { sliceForApp, type MemorySlice } from './slice.js';

/**
 * Default file path. Tests inject a different path via the options.
 */
export const DEFAULT_PATH = join(
  process.env.HOME ?? process.env.USERPROFILE ?? '.',
  '.duya',
  'computer-use',
  'memory.md',
);

const FILE_HEADER = `# Computer Use Memory

> Auto-generated by Computer Use Mode. Edit freely — the agent will re-read on next session.

Last updated: `;

export interface ComputerUseMemoryOptions {
  /** Override file path. Defaults to ~/.duya/computer-use/memory.md. */
  filePath?: string;
  /** Override now() for deterministic tests. */
  now?: () => Date;
}

export interface MemoryEntry {
  /** App name (used as section heading). */
  app: string;
  /** Bullet text. Single line; caller splits into multiple entries. */
  note: string;
  /** ISO timestamp when the entry was added. */
  ts?: string;
}

/**
 * Parse a memory.md file into a structured form. The file format is
 * forgiving: missing header / extra blank lines / unknown top-level
 * lines are tolerated.
 *
 * Returns an array of { app, note, ts } entries. Order is preserved
 * (insertion order). Top-level lines outside `## App` sections are
 * ignored.
 */
export function parseMemory(text: string): MemoryEntry[] {
  const out: MemoryEntry[] = [];
  let currentApp: string | null = null;
  const lines = text.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    if (line.startsWith('# ')) {
      // Top-level title — skip.
      continue;
    }
    if (line.startsWith('## ')) {
      currentApp = line.slice(3).trim();
      continue;
    }
    if (currentApp === null) continue;
    if (line.length === 0) continue;
    // Bullet detection: support `- `, `* `, `+ `, and numbered `1. `.
    const match = line.match(/^\s*(?:[-*+]|\d+\.)\s+(.*)$/);
    if (!match) continue;
    const note = (match[1] ?? '').trim();
    if (note.length === 0) continue;
    // Strip trailing `  <!-- ts:ISO -->` metadata if present.
    let ts: string | undefined;
    const tsMatch = note.match(/^(.*?)\s*<!--\s*ts:\s*([^>]+?)\s*-->\s*$/);
    if (tsMatch && tsMatch[2]) {
      out.push({ app: currentApp, note: tsMatch[1]!, ts: tsMatch[2] });
    } else {
      out.push({ app: currentApp, note });
    }
  }
  return out;
}

/**
 * Serialize an entries list into the canonical memory.md format.
 *
 * Sections are grouped by app (alphabetical), with the canonical
 * header + Last updated line.
 */
export function serializeMemory(
  entries: ReadonlyArray<MemoryEntry>,
  now: () => Date = () => new Date(),
): string {
  const groups = new Map<string, MemoryEntry[]>();
  for (const e of entries) {
    const list = groups.get(e.app) ?? [];
    list.push(e);
    groups.set(e.app, list);
  }

  const lines: string[] = [];
  lines.push(FILE_HEADER + now().toISOString());
  lines.push('');
  for (const app of [...groups.keys()].sort((a, b) => a.localeCompare(b))) {
    lines.push(`## ${app}`);
    lines.push('');
    const items = groups.get(app)!;
    for (const e of items) {
      if (e.ts) {
        lines.push(`- ${e.note}  <!-- ts:${e.ts} -->`);
      } else {
        lines.push(`- ${e.note}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Memory accessor. Phase 3 ships read / append / sliceForApp.
 * Operations are async to match Node fs semantics; the caller should
 * batch where possible.
 */
export class ComputerUseMemory {
  private readonly filePath: string;
  private readonly now: () => Date;

  constructor(opts: ComputerUseMemoryOptions = {}) {
    this.filePath = opts.filePath ?? DEFAULT_PATH;
    this.now = opts.now ?? (() => new Date());
  }

  /** Resolve the file path (useful for tests + audit logs). */
  getFilePath(): string {
    return this.filePath;
  }

  /** True when the file exists on disk. */
  exists(): boolean {
    try {
      return existsSync(this.filePath);
    } catch {
      return false;
    }
  }

  /** Read all entries from disk. Empty list when the file does not exist. */
  async read(): Promise<MemoryEntry[]> {
    if (!this.exists()) return [];
    const raw = await readFile(this.filePath, 'utf-8');
    return parseMemory(raw);
  }

  /**
   * Append a single note. Creates the parent directory if needed.
   * Existing entries are preserved verbatim; the new entry is grouped
   * under the matching `## app` section, or a new section is created.
   *
   * Returns the new entry as written (with ts populated).
   */
  async append(entry: MemoryEntry): Promise<MemoryEntry> {
    const entries = await this.read();
    const ts = entry.ts ?? this.now().toISOString();
    const next: MemoryEntry = { app: entry.app, note: entry.note, ts };
    entries.push(next);
    await this.write(entries);
    return next;
  }

  /**
   * Bulk-write the entries list. The on-disk file is replaced
   * atomically with a single writeFile call; partial writes are
   * tolerated (the file either has the old content or the new one).
   */
  async write(entries: ReadonlyArray<MemoryEntry>): Promise<void> {
    await mkdir(dirname(this.filePath), { recursive: true });
    const body = serializeMemory(entries, this.now);
    await writeFile(this.filePath, body, 'utf-8');
  }

  /**
   * Slice the memory for a single app. Returns the matching entries
   * + an optional token-budgeted text suitable for sub-agent prompts.
   *
   * Delegates to `sliceForApp` so the policy lives in one place.
   */
  async sliceForApp(
    app: string,
    tokenBudget?: number,
  ): Promise<MemorySlice> {
    const entries = await this.read();
    return sliceForApp(entries, app, tokenBudget);
  }
}

/**
 * Convenience constructor for the canonical ~/.duya path. Used by
 * the agent tool layer; tests should use `new ComputerUseMemory({...})`.
 */
export function getDefaultMemory(): ComputerUseMemory {
  return new ComputerUseMemory();
}