// AUTO-GENERATED by scripts/inline-modules.mjs — DO NOT EDIT BY HAND.
// Source files: packages/agent/src/modules/<name>/README.md
// Regenerate with: node scripts/inline-modules.mjs
export const INLINE_DIAGRAM = `# Diagram Module — SVG Flowcharts / Architecture / Structure

Design specification for SVG-based diagrams: flowcharts, architecture diagrams, sequence diagrams, structure charts. Load this module before calling \`show_widget\` for any SVG diagram.

---

## Design Philosophy

- **Flat**: No gradients, no shadows, no blur.
- **Transparent background**: Never set \`background\` on body or outermost element.
- **Minimum font size 11px**.
- **Font weight 400 and 500 only**: Never use 600 or 700.
- **Sentence case only**: No Title Case, no ALL CAPS — including node labels.
- **Text explanations go in the chat**: Widget output contains only the SVG.
- **Pre-plan coordinates before writing SVG**: List layers, node counts, and calculated dimensions in a comment block first. Never improvise coordinates.
- **No \`display: none\` during streaming**: Flickers during DOM diff.

---

## CSS Variables (宿主已注入，直接使用)

| Variable | Usage |
|----------|-------|
| \`var(--color-text-primary)\` | Fallback text |
| \`var(--color-text-secondary)\` | Dim labels |
| \`var(--color-border-tertiary)\` | Connector lines without class |
| \`var(--accent)\` | Highlight stroke |
| \`var(--font-sans)\` | foreignObject text (如需) |

**大多数情况下直接使用下方预注入的 class，不需要手写颜色变量。**

---

## SVG Diagram Classes (宿主已预注入到 iframe，直接使用)

### Container colors (用于 \`<rect>\`)

| Class | 颜色语义 | 适用场景 |
|-------|---------|---------|
| \`.s-plat\` | Deep Blue | OS、外部平台、顶层 shell |
| \`.s-proc\` | Blue | 主进程、核心层 |
| \`.s-agent\` | Green | Agent 流程、成功路径 |
| \`.s-msg\` | Purple | IPC、消息、通信节点 |
| \`.s-err\` | Red | 错误、危险 |
| \`.s-chk\` | Amber | 检查点、决策节点 |
| \`.s-sub\` | Gray | 浅色背景内的子组件 |
| \`.s-sub-dark\` | Dark Gray | 深色背景内的子组件 |

### Text colors (用于 \`<text>\`)

| Class | 适用场景 |
|-------|---------|
| \`.t-dark\` | 标题文字，位于 \`.s-plat\` 上 |
| \`.t-dim\` | 副标题文字，位于 \`.s-plat\` 上 |
| \`.t-light\` | 标题文字，位于 \`.s-proc\` 上 |
| \`.t-green\` | 标题文字，位于 \`.s-agent\` 上 |
| \`.t-gray\` | 标题文字，位于 \`.s-sub\` 上 |
| \`.t-gray-dim\` | 副标题文字，位于 \`.s-sub\` 上 |
| \`.td-on-dark\` | 标题文字，位于 \`.s-sub-dark\` 上 |
| \`.td-on-dark-dim\` | 副标题文字，位于 \`.s-sub-dark\` 上 |

**规则**：文字 class 必须与背景 class 配对使用，禁止在有色背景上用 \`fill="black"\` 或 \`fill="inherit"\`。

### Typography

| Class | 样式 | 用途 |
|-------|------|------|
| \`.tt\` | 14px, font-weight 500, text-anchor middle | 节点标题 |
| \`.td\` | 12px, font-weight 400, text-anchor middle | 节点副标题/描述 |

### Layout

| Class | 用途 |
|-------|------|
| \`.c-bx\` | 外层容器矩形，\`rx=10\` |
| \`.n-box\` | 内层节点矩形，\`rx=6\` |
| \`.arr-line\` | 箭头连线 |

---

## Coordinate Calculation (必须先算，再写 SVG)

在写任何 SVG 坐标之前，先在注释里列出计划：

\`\`\`
<!-- PLAN
  Layers: 3
  Layer 1: 1 node  → node_width = 620
  Layer 2: 3 nodes → node_width = (620 - 2×16) / 3 = 196
  Layer 3: 2 nodes → node_width = (620 - 1×16) / 2 = 302
  Node heights: all 44px (single-line)
  H = 20 + 3×(44+20) + 30 = 242
  viewBox: 0 0 680 242
-->
\`\`\`

**公式**：

\`\`\`
viewBox width:  680 (固定)
viewBox height: H = 20 + (层数 × (节点高 + 层间距20)) + 30

同行 N 个节点的宽度：
  node_width = (620 − (N−1) × 16) / N

节点起始 x（第 i 个，从0计）：
  x = 30 + i × (node_width + 16)

文字 y 坐标（单行节点）：
  y = rect.y + 22  (= rect.y + rect.height/2，配合 dominant-baseline="middle")

文字属性必须加：
  dominant-baseline="middle"  text-anchor="middle"
\`\`\`

节点高度参考：
- 单行文字（仅 \`.tt\`）：44px
- 双行文字（\`.tt\` + \`.td\`）：60px，标题 y = rect.y+20，副标题 y = rect.y+40

---

## Arrow Marker (每个含箭头的 SVG 必须包含)

\`\`\`svg
<defs>
  <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5"
          markerWidth="6" markerHeight="6" orient="auto-start-reverse">
    <path d="M2 1L8 5L2 9" fill="none" stroke="context-stroke"
          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  </marker>
</defs>
\`\`\`

\`context-stroke\` 让箭头头自动继承线条颜色，不需要单独设置。

连线示例：
\`\`\`svg
<line x1="340" y1="84" x2="340" y2="100"
      class="arr-line" marker-end="url(#arrow)"/>
\`\`\`

---

## Color Usage Rules

- 每张图最多使用 2 个语义色 ramp（不算 gray）
- Gray（\`.s-sub\`）用于中性/结构节点
- 颜色按**节点类型**分配，不按顺序循环

---

## NEVER

- \`fill="black"\` 或 \`fill="inherit"\` 加在 \`<text>\` 上
- 箭头穿越不相关节点
- 渐变、阴影、blur
- 不经过计算直接猜坐标
- 超过 2 个语义色 ramp

---

## Reference Example (3-layer architecture)

\`\`\`svg
<!-- PLAN
  Layer 1: 1 wide node (platform shell)，含2个子节点
  Layer 2: 2 nodes side-by-side
  Node heights: outer 60px, inner 34px
  H = 20 + (60+20) + (80+20) + 30 = 230
-->
<svg width="100%" viewBox="0 0 680 230" role="img" xmlns="http://www.w3.org/2000/svg">
<title>Three-layer architecture</title>
<desc>Platform shell containing two sub-nodes on top, two process nodes below</desc>
<defs>
  <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5"
          markerWidth="6" markerHeight="6" orient="auto-start-reverse">
    <path d="M2 1L8 5L2 9" fill="none" stroke="context-stroke"
          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  </marker>
</defs>

<!-- Layer 1: Platform shell -->
<rect x="30" y="20" width="620" height="60" class="s-plat c-bx"/>
<text x="340" y="38" class="tt t-dark" dominant-baseline="middle" text-anchor="middle">Platform</text>
<rect x="50" y="36" width="260" height="34" class="s-sub-dark n-box"/>
<text x="180" y="53" class="tt td-on-dark" dominant-baseline="middle" text-anchor="middle">Main process</text>
<rect x="370" y="36" width="260" height="34" class="s-sub-dark n-box"/>
<text x="500" y="53" class="tt td-on-dark" dominant-baseline="middle" text-anchor="middle">Renderer</text>

<!-- Layer 2: Two process nodes -->
<rect x="30" y="120" width="296" height="60" class="s-proc c-bx"/>
<text x="178" y="143" class="tt t-light" dominant-baseline="middle" text-anchor="middle">Agent layer</text>
<rect x="46" y="154" width="264" height="16" class="s-sub n-box"/>
<text x="178" y="162" class="td t-gray" dominant-baseline="middle" text-anchor="middle">ConductorAgent</text>

<rect x="354" y="120" width="296" height="60" class="s-agent c-bx"/>
<text x="502" y="143" class="tt t-green" dominant-baseline="middle" text-anchor="middle">Widget layer</text>
<rect x="370" y="154" width="264" height="16" class="s-sub n-box"/>
<text x="502" y="162" class="td t-gray" dominant-baseline="middle" text-anchor="middle">CanvasStore</text>

<!-- Arrows -->
<line x1="178" y1="80" x2="178" y2="120" class="arr-line" marker-end="url(#arrow)"/>
<line x1="502" y1="80" x2="502" y2="120" class="arr-line" marker-end="url(#arrow)"/>
</svg>
\`\`\`

---

## Tag Classes (状态/复杂度标签，可用于节点内或图例)

\`\`\`
.tag-t  → success-soft bg / success text  (低复杂度、已完成)
.tag-a  → warning-soft bg / warning text  (中等、进行中)
.tag-r  → error-soft bg / error text      (高复杂度、阻塞)
.tag-p  → accent-soft bg / accent text    (特殊、强调)
.tag-gray → secondary bg / secondary text (中性)
\`\`\``;

export const INLINE_MOCKUP = `# Mockup Module — HTML Cards / Dashboards / UI Components

Design specification for HTML-based visual components: data cards, dashboards, comparison grids, key-value summaries, status boards. Load this module before calling \`show_widget\` for any card or dashboard widget.

---

## Design Philosophy

- **Flat**: No gradients, no shadows, no blur effects.
- **Transparent background**: Never set \`background\` on body or outermost container.
- **Minimum font size 11px**.
- **Font weight 400 and 500 only**: Never use 600 or 700.
- **Sentence case only**: No Title Case, no ALL CAPS — including card titles, labels, tags.
- **Text explanations go in the chat**: Widget output contains only visual elements.
- **No \`position: fixed\`**: Causes iframe height collapse.
- **No CSS animations**: Host adds reveal animation automatically.
- **No \`display: none\` during streaming**: Flickers. Stack content vertically; use JS toggling only post-stream.
- **No nested scrolling**: Height auto-fits. Do not set \`overflow: auto\` on inner containers.
- **Round every displayed number**: Any number shown to the user must pass through \`Math.round()\`, \`.toFixed(n)\`, or \`Intl.NumberFormat\`.
- **Text on colored background**: Always use the dark end of the same color family, never plain black or \`var(--color-text-primary)\`.
- **Single-side borders get no border-radius**: If using \`border-left\` or \`border-top\` accent, set \`border-radius: 0\`.
- **No React / JSX**: Widget code is raw HTML. No transpiler available.

---

## CSS Variables (宿主已注入，直接使用)

| Variable | Usage |
|----------|-------|
| \`var(--color-background-primary)\` | Card background |
| \`var(--color-background-secondary)\` | Note background, tag bg, metric card bg |
| \`var(--color-text-primary)\` | Card titles, body text |
| \`var(--color-text-secondary)\` | Values, subtitles |
| \`var(--color-text-tertiary)\` | Labels, dim content, hints |
| \`var(--color-border-tertiary)\` | Card borders, dividers |
| \`var(--accent)\` | Primary accent stroke, highlighted value |
| \`var(--accent-soft)\` | Highlighted card border (2px, only exception) |
| \`var(--success)\` / \`var(--success-soft)\` | Positive, done |
| \`var(--warning)\` / \`var(--warning-soft)\` | Medium, in progress |
| \`var(--error)\` / \`var(--error-soft)\` | Negative, blocked |
| \`var(--font-sans)\` | All UI text |
| \`var(--font-mono)\` | Numeric values, code snippets |
| \`var(--border-radius-md)\` | Inner elements, tags, chips (8px) |
| \`var(--border-radius-lg)\` | Cards and containers (12px) |

---

## Utility Classes (宿主已注入，直接使用)

\`\`\`
Flex:    .flex .flex-col .flex-row .flex-wrap .items-center .justify-center .justify-between
Grid:    .grid .grid-cols-2 .grid-cols-3 .grid-cols-4
Spacing: .gap-1 .gap-2 .gap-3 .gap-4 / .p-1 .p-2 .p-3 .p-4
Text:    .text-xs .text-sm .text-base .text-lg .text-xl .text-2xl
         .text-center .text-left .text-right
         .font-bold .font-semibold .font-mono
Size:    .w-full .h-full
Overflow:.overflow-auto .overflow-hidden
\`\`\`

---

## Component Rules

### Borders
- Default card border: \`0.5px solid var(--color-border-tertiary)\`
- Highlighted/featured card: \`2px solid var(--accent-soft)\` — 唯一允许使用 2px 的情形
- Dividers: \`0.5px solid var(--color-border-tertiary)\`
- Single-side accent (\`border-left\`): \`border-radius: 0\` — 禁止在单侧 border 上加圆角

### Border Radius
- Cards and containers: \`var(--border-radius-lg)\` (12px)
- Inner elements, tags: \`var(--border-radius-md)\` (8px)
- Inline chips: \`4px\`

### Icons
- 使用 **Tabler outline** 字体 (\`ti ti-*\` class)，不要手绘 SVG path
- 大小：16px inline，24px 最大装饰
- 颜色：\`var(--color-text-secondary)\` 或跟随父元素颜色
- 装饰性图标加 \`aria-hidden="true"\`

---

## Card Layout Pattern

\`\`\`html
<style>
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 12px; }
.card { background: var(--color-background-primary); border: 0.5px solid var(--color-border-tertiary); border-radius: var(--border-radius-lg); overflow: hidden; }
.card-head { padding: 10px 14px 8px; border-bottom: 0.5px solid var(--color-border-tertiary); display: flex; align-items: center; gap: 8px; }
.card-head i { font-size: 16px; color: var(--color-text-secondary); }
.card-title { font-size: 13px; font-weight: 500; color: var(--color-text-primary); }
.card-body { padding: 12px 14px; display: flex; flex-direction: column; gap: 8px; }
.row { display: flex; gap: 6px; align-items: flex-start; }
.label { font-size: 11px; color: var(--color-text-tertiary); min-width: 64px; padding-top: 1px; flex-shrink: 0; }
.val { font-size: 12px; color: var(--color-text-secondary); line-height: 1.5; font-family: var(--font-mono); }
.note { font-size: 11px; color: var(--color-text-tertiary); line-height: 1.5; padding: 6px 8px; background: var(--color-background-secondary); border-radius: 6px; margin-top: 2px; }
.divider { height: 0.5px; background: var(--color-border-tertiary); margin: 2px 0; }
</style>

<div class="grid">
  <div class="card">
    <div class="card-head">
      <i class="ti ti-database" aria-hidden="true"></i>
      <span class="card-title">Storage</span>
    </div>
    <div class="card-body">
      <div class="row">
        <span class="label">Total</span>
        <span class="val">128 GB</span>
      </div>
      <div class="row">
        <span class="label">Used</span>
        <span class="val">42.3 GB</span>
      </div>
      <div class="divider"></div>
      <div class="note">Last synced 3 minutes ago</div>
    </div>
  </div>
</div>
\`\`\`

---

## Metric Card Pattern (数字摘要卡)

\`\`\`html
<style>
.metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 10px; }
.metric { background: var(--color-background-secondary); border-radius: var(--border-radius-md); padding: 14px 16px; }
.metric-label { font-size: 11px; color: var(--color-text-tertiary); margin-bottom: 4px; }
.metric-value { font-size: 24px; font-weight: 500; color: var(--color-text-primary); font-family: var(--font-mono); line-height: 1.1; }
.metric-sub { font-size: 11px; color: var(--color-text-tertiary); margin-top: 2px; }
</style>

<div class="metrics">
  <div class="metric">
    <div class="metric-label">Total requests</div>
    <div class="metric-value">12,847</div>
    <div class="metric-sub">↑ 8% vs last week</div>
  </div>
  <div class="metric">
    <div class="metric-label">Error rate</div>
    <div class="metric-value" style="color: var(--error);">0.3%</div>
    <div class="metric-sub">Below threshold</div>
  </div>
</div>
\`\`\`

---

## Tag / Badge Classes (宿主已预注入)

\`\`\`html
<span class="tag tag-t">Done</span>
<span class="tag tag-a">In progress</span>
<span class="tag tag-r">Blocked</span>
<span class="tag tag-p">Preview</span>
<span class="tag tag-gray">Neutral</span>
\`\`\`

| Class | bg / text | 用途 |
|-------|-----------|------|
| \`.tag-t\` | \`success-soft\` / \`success\` | 低复杂度、已完成、正面 |
| \`.tag-a\` | \`warning-soft\` / \`warning\` | 中等、进行中 |
| \`.tag-r\` | \`error-soft\` / \`error\` | 高复杂度、阻塞 |
| \`.tag-p\` | \`accent-soft\` / \`accent\` | 特殊、Preview、强调 |
| \`.tag-gray\` | \`secondary\` bg / \`secondary\` text | 中性、默认 |

---

## Comparison Card Pattern (对比/决策场景)

\`\`\`html
<!-- 推荐项用 2px accent 边框 + 角标，其他保持默认 -->
<div class="card" style="border: 2px solid var(--accent-soft); position: relative;">
  <span class="tag tag-p" style="position: absolute; top: -1px; right: 12px; border-radius: 0 0 4px 4px;">
    Recommended
  </span>
  <!-- card content -->
</div>
\`\`\`

---

## Avatar / Initials Circle

\`\`\`html
<div style="
  width: 40px; height: 40px;
  border-radius: 50%;
  background: var(--accent-soft);
  display: flex; align-items: center; justify-content: center;
  font-size: 14px; font-weight: 500;
  color: var(--accent);
">CX</div>
\`\`\`

---

## CDN (仅允许以下域名，其他被 CSP 拦截)

\`\`\`
cdnjs.cloudflare.com   cdn.jsdelivr.net   unpkg.com   esm.sh
\`\`\`

---

## Streaming Constraints

输出顺序：\`<style>\` → 内容 HTML → \`<script>\`

---

## Anti-Patterns

\`\`\`
✗ position: fixed
✗ display: none 在流式期间
✗ 嵌套滚动容器（overflow: auto on inner divs）
✗ 单侧 border 加 border-radius
✗ 有色背景上用 var(--color-text-primary) 或黑色文字
✗ font-weight: 600 / 700
✗ 渐变、阴影、blur
✗ 展示未 round 的浮点数
✗ 手绘 SVG 图标（用 Tabler ti-* 代替）
✗ 超过 2px 的 border（除高亮卡片外）
\`\`\``;

export const INLINE_CHART = `# Chart Module — Data Visualization (Chart.js / D3)

Design specification for data chart widgets. Load this module before calling \`show_widget\` for any chart or data visualization.

---

## Design Philosophy

- **Flat**: No gradients, no shadows, no blur. Charts must be clean and readable.
- **Transparent background**: Never set \`background\` on body or outermost container. Host provides the canvas.
- **Minimum font size 11px** for axis labels and legends.
- **Font weight 400 and 500 only**: Never use 600 or 700.
- **Sentence case only**: No Title Case, no ALL CAPS — including axis labels and legend text.
- **Text explanations go in the chat**: Widget output contains only the chart itself.
- **Round every displayed number**: JS float math leaks (0.1+0.2 = 0.30000000000000004). Any number reaching the screen must go through \`Math.round()\`, \`.toFixed(n)\`, or \`Intl.NumberFormat\`. Set \`step="1"\` on range sliders.
- **No \`display: none\` during streaming**: Hidden content streams invisibly. Stack all states vertically or use JS-driven toggling only after streaming completes.

---

## CSS Variables (宿主已注入，直接使用)

| Variable | Usage |
|----------|-------|
| \`var(--color-background-primary)\` | Chart container background |
| \`var(--color-background-secondary)\` | Tooltip background, legend area |
| \`var(--color-text-primary)\` | Chart title, primary labels |
| \`var(--color-text-secondary)\` | Axis labels, legend text |
| \`var(--color-border-tertiary)\` | Grid lines, tick marks |
| \`var(--accent)\` | Primary series, highlight |
| \`var(--accent-soft)\` | Hover state, selected bar |
| \`var(--success)\` / \`var(--success-soft)\` | Positive / growth series |
| \`var(--warning)\` / \`var(--warning-soft)\` | Medium / neutral series |
| \`var(--error)\` / \`var(--error-soft)\` | Negative / error series |
| \`var(--font-sans)\` | All chart text |
| \`var(--font-mono)\` | Tick labels, data labels |
| \`var(--border-radius-md)\` | Tooltip, legend box corners |

**禁止使用**: 任何未在上表列出的自定义变量（如 \`--bg-canvas\`、\`--text\`、\`--border\` 等不存在于宿主）。

---

## Utility Classes (宿主已注入，可直接使用)

\`\`\`
Flex:    .flex .flex-col .flex-row .items-center .justify-center .justify-between
Grid:    .grid .grid-cols-2 .grid-cols-3 .grid-cols-4
Spacing: .gap-1 .gap-2 .gap-3 .gap-4 / .p-1 .p-2 .p-3 .p-4
Text:    .text-xs .text-sm .text-base .font-mono
Size:    .w-full .h-full
\`\`\`

---

## Multi-Series Color Palette

使用顺序固定，确保在浅色和深色背景下都有足够对比度：

\`\`\`
#4f8cff  (Blue)     #ff6b6b  (Red)      #ffd93d  (Yellow)
#6ee7b7  (Green)    #a78bfa  (Purple)   #fb923c  (Orange)
#67e8f9  (Cyan)     #f472b6  (Pink)     #a3e635  (Lime)
\`\`\`

单系列图表优先用 \`var(--accent)\`，不要硬编码颜色。

---

## CDN (仅允许以下域名，其他被 CSP 拦截)

\`\`\`
cdnjs.cloudflare.com   cdn.jsdelivr.net   unpkg.com   esm.sh
\`\`\`

---

## Streaming Constraints

输出顺序必须严格遵守：\`<style>\` → 内容 HTML → \`<script>\`

Chart.js / D3 需要 DOM 节点存在才能初始化，\`<script>\` 必须在最后。

---

## Chart.js Example

\`\`\`html
<style>
.chart-wrap { width: 100%; max-width: 620px; margin: 0 auto; }
canvas { width: 100% !important; }
</style>

<div class="chart-wrap">
  <canvas id="chart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script>
const ctx = document.getElementById('chart').getContext('2d');
const style = getComputedStyle(document.documentElement);
const textColor = style.getPropertyValue('--color-text-secondary').trim();
const gridColor = style.getPropertyValue('--color-border-tertiary').trim();
const accent = style.getPropertyValue('--accent').trim();

new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ['Jan', 'Feb', 'Mar', 'Apr'],
    datasets: [{
      label: 'Users',
      data: [120, 145, 180, 210],
      backgroundColor: accent,
      borderWidth: 0,
      borderRadius: 4
    }]
  },
  options: {
    responsive: true,
    plugins: {
      legend: { display: false }
    },
    scales: {
      y: {
        beginAtZero: true,
        grid: { color: gridColor },
        ticks: { font: { size: 11 }, color: textColor }
      },
      x: {
        grid: { display: false },
        ticks: { font: { size: 11 }, color: textColor }
      }
    }
  }
});
</script>
\`\`\`

**关键点**：通过 \`getComputedStyle\` 读取 CSS 变量再传给 Chart.js，而不是直接在 options 里写 \`var(--accent)\`（Chart.js 不解析 CSS 变量）。

---

## D3.js Example

\`\`\`html
<style>
#chart { width: 100%; height: 300px; }
</style>
<div id="chart"></div>
<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script>
const style = getComputedStyle(document.documentElement);
const accent = style.getPropertyValue('--accent').trim();
const textColor = style.getPropertyValue('--color-text-secondary').trim();

const data = [
  { name: 'Q1', value: 120 },
  { name: 'Q2', value: 145 },
  { name: 'Q3', value: 180 },
  { name: 'Q4', value: 210 }
];

const margin = { top: 20, right: 20, bottom: 36, left: 44 };
const container = document.getElementById('chart');
const W = container.clientWidth || 620;
const H = 300;
const w = W - margin.left - margin.right;
const h = H - margin.top - margin.bottom;

const svg = d3.select('#chart').append('svg')
  .attr('width', W).attr('height', H);
const g = svg.append('g')
  .attr('transform', \`translate(\${margin.left},\${margin.top})\`);

const x = d3.scaleBand().domain(data.map(d => d.name)).range([0, w]).padding(0.3);
const y = d3.scaleLinear().domain([0, d3.max(data, d => d.value)]).nice().range([h, 0]);

g.append('g').attr('transform', \`translate(0,\${h})\`).call(d3.axisBottom(x))
  .selectAll('text').style('fill', textColor).style('font-size', '11px');
g.append('g').call(d3.axisLeft(y).ticks(5))
  .selectAll('text').style('fill', textColor).style('font-size', '11px');

g.selectAll('rect').data(data).join('rect')
  .attr('x', d => x(d.name))
  .attr('y', d => y(d.value))
  .attr('width', x.bandwidth())
  .attr('height', d => h - y(d.value))
  .attr('fill', accent)
  .attr('rx', 3);
</script>
\`\`\`

---

## Best Practices

- 单系列图表隐藏 legend（\`legend: { display: false }\`）
- 柱状图始终 \`beginAtZero: true\`，除非有明确理由不这样做
- 坐标轴标签简短清晰
- 饼图不超过 5 个分类，超过用柱状图代替
- 保持数据内联，禁止在 widget 内发起 API 请求
- 不要用 \`sendPrompt\` 做计算，计算逻辑放 JS`;

export const INLINE_INTERACTIVE = `# Interactive Module — Calculators / Mini-Apps / Explainers

Design specification for interactive widgets: calculators, converters, sliders, steppers, mini-apps with user controls. Load this module before calling \`show_widget\` for any widget with user interaction.

---

## Design Philosophy

- **Flat**: No gradients, no shadows, no blur effects.
- **Transparent background**: Never set \`background\` on body or outermost container.
- **Minimum font size 11px**: Controls and labels must be readable.
- **Font weight 400 and 500 only**: Never use 600 or 700.
- **Sentence case only**: No Title Case, no ALL CAPS.
- **Text explanations go in the chat**: Widget contains only the interactive element.
- **No \`position: fixed\`**: Causes iframe height collapse.
- **No CSS animations**: Host adds a reveal animation automatically.
- **No \`localStorage\` / \`sessionStorage\`**: Sandboxed iframe blocks these APIs entirely — they throw, they do not silently fail.
- **No \`display: none\` during streaming**: Hidden content streams invisibly. Use JS-driven toggling only after streaming completes.
- **Round every displayed number**: \`0.1 + 0.2 = 0.30000000000000004\`. Any number shown to the user must pass through \`Math.round()\`, \`.toFixed(n)\`, or \`Intl.NumberFormat\`. Set \`step="1"\` (or appropriate step) on range sliders.
- **No React / JSX**: Widget code is raw HTML. No transpiler available.

---

## CSS Variables (宿主已注入，直接使用)

| Variable | Usage |
|----------|-------|
| \`var(--color-background-primary)\` | Container background, card bg |
| \`var(--color-background-secondary)\` | Input fields, result areas, tag bg |
| \`var(--color-text-primary)\` | Primary labels, result values |
| \`var(--color-text-secondary)\` | Secondary labels, descriptions |
| \`var(--color-text-tertiary)\` | Placeholder, hints |
| \`var(--color-border-tertiary)\` | Input borders, section dividers |
| \`var(--accent)\` | Primary button bg, active state |
| \`var(--accent-soft)\` | Button hover, selected state |
| \`var(--success)\` / \`var(--success-soft)\` | Success result |
| \`var(--warning)\` / \`var(--warning-soft)\` | Warning state |
| \`var(--error)\` / \`var(--error-soft)\` | Error state, invalid input |
| \`var(--font-sans)\` | All UI text |
| \`var(--font-mono)\` | Numeric outputs, code |
| \`var(--border-radius-md)\` | Inputs, buttons (8px) |
| \`var(--border-radius-lg)\` | Cards, containers (12px) |

---

## Utility Classes (宿主已注入，直接使用)

\`\`\`
Flex:    .flex .flex-col .flex-row .flex-wrap .items-center .justify-center .justify-between
Grid:    .grid .grid-cols-2 .grid-cols-3 .grid-cols-4
Spacing: .gap-1 .gap-2 .gap-3 .gap-4 / .p-1 .p-2 .p-3 .p-4
Text:    .text-xs .text-sm .text-base .text-lg .text-xl .text-2xl
         .text-center .text-left .text-right
         .font-bold .font-semibold .font-mono
Size:    .w-full .h-full
Overflow:.overflow-auto .overflow-hidden
\`\`\`

---

## Component Rules

### Borders
- Default: \`0.5px solid var(--color-border-tertiary)\`
- Focus ring: \`box-shadow: 0 0 0 2px var(--accent-soft)\` (no outline)

### Border Radius
- Inputs and buttons: \`var(--border-radius-md)\` (8px)
- Cards and containers: \`var(--border-radius-lg)\` (12px)
- Inline chips / tags: \`4px\`

### Inputs
\`\`\`css
padding: 6px 10px;
font-size: 13px;
font-family: var(--font-sans);
border: 0.5px solid var(--color-border-tertiary);
border-radius: var(--border-radius-md);
background: var(--color-background-secondary);
color: var(--color-text-primary);
\`\`\`

### Buttons
\`\`\`css
/* Default */
display: inline-flex;
align-items: center;
gap: 6px;
padding: 6px 14px;
font-size: 13px;
font-weight: 500;
font-family: var(--font-sans);
border: 0.5px solid var(--color-border-tertiary);
border-radius: var(--border-radius-md);
background: var(--color-background-primary);
color: var(--color-text-primary);
cursor: pointer;

/* Primary variant */
background: var(--accent);
color: #fff;
border-color: var(--accent);
\`\`\`

\`\`\`html
<!-- Button template -->
<button class="btn" onclick="compute()">Calculate</button>
<button class="btn btn-primary" onclick="compute()">Run</button>
\`\`\`

### Range Sliders
\`\`\`html
<input type="range" min="0" max="100" value="50" step="1" id="slider">
\`\`\`
Always read value as \`parseInt(el.value, 10)\` or \`parseFloat(el.value)\` — never display raw \`.value\` string.

---

## sendPrompt(text) — Global Function

宿主注入的全局函数，调用后相当于用户在对话框发送了一条消息。

\`\`\`html
<!-- 触发跟进问题 -->
<button onclick="sendPrompt('Explain why this result is negative')">Why negative?</button>

<!-- 请求相关内容 -->
<button onclick="sendPrompt('Show me the architecture diagram')">Show diagram</button>

<!-- 声明式写法 -->
<button data-send-message="Explain this calculation">Explain</button>
\`\`\`

**什么时候用 sendPrompt**：
- 请求 Claude 解释、扩展、或生成相关内容
- 跳转到另一个话题或请求新的 widget

**什么时候不用 sendPrompt（直接用 JS）**：
- 计算、换算、排序、过滤 — 这些在 JS 里做，0 延迟
- 表单验证、输入格式化
- 切换显示状态

> 错误模式：用户点击"Calculate"→ \`sendPrompt('calculate: ' + inputs)\` → 等待 Claude 响应
> 正确模式：用户点击"Calculate"→ JS 直接算 → 立刻更新 DOM

---

## CDN (仅允许以下域名，其他被 CSP 拦截)

\`\`\`
cdnjs.cloudflare.com   cdn.jsdelivr.net   unpkg.com   esm.sh
\`\`\`

---

## Streaming Constraints

输出顺序必须严格遵守：\`<style>\` → 内容 HTML → \`<script>\`

DOM 必须在脚本执行前存在，所有 \`addEventListener\` 和初始化逻辑放在最后的 \`<script>\` 里。

---

## Format Template

\`\`\`html
<style>
/* 样式放最前 */
.container { ... }
.btn { ... }
</style>

<div class="container p-3">
  <!-- 控件 -->
  <div class="flex gap-2 items-center">
    <label class="text-sm" style="color: var(--color-text-secondary);">Years</label>
    <input type="range" min="1" max="40" value="20" step="1" id="years">
    <span class="font-mono text-sm" id="years-out">20</span>
  </div>

  <!-- 结果区域 -->
  <div style="
    background: var(--color-background-secondary);
    border-radius: var(--border-radius-md);
    padding: 12px 16px;
    margin-top: 12px;
  ">
    <span style="font-size: 11px; color: var(--color-text-tertiary);">Result</span>
    <div class="font-mono text-2xl" id="result" style="color: var(--color-text-primary);">—</div>
  </div>
</div>

<script>
/* JS 放最后 */
const slider = document.getElementById('years');
const out = document.getElementById('years-out');
const result = document.getElementById('result');

function compute() {
  const n = parseInt(slider.value, 10);
  out.textContent = n;
  // 计算逻辑，记得 round
  result.textContent = Math.round(1000 * Math.pow(1.07, n)).toLocaleString();
}

slider.addEventListener('input', compute);
compute(); // 初始化
</script>
\`\`\`

---

## Anti-Patterns

\`\`\`
✗ position: fixed
✗ localStorage / sessionStorage
✗ display: none 在流式期间
✗ 展示未 round 的浮点数
✗ sendPrompt 做计算
✗ font-weight: 600 / 700
✗ 渐变、阴影、blur
✗ 外部 API 调用（非 CDN 域名）
\`\`\``;
