/**
 * Phase 3 — semantic memory summary synthesizer.
 *
 * Pipeline: Phase 1 extracts rollouts → Phase 2 curates them into
 * canonical files (`global/{areas,people,preferences}/`) → Phase 3
 * distills the whole canonical store into the *semantic* `summary.md`
 * that gets inlined into the agent's system prompt as MEMORY_SUMMARY.
 *
 * The old `summary.md` was a pure deterministic routing table
 * (`- [area] <first-paragraph-snippet>`). It told the agent which files
 * exist but not who the user is, what matters most, or how to find the
 * right memory. This synthesizer keeps that index (the agent still needs
 * it to locate files) and prepends a semantic digest generated by the LLM:
 *
 *   1. profile    — who the user is (cross-file synthesis, not per-file)
 *   2. top_rules  — the N most important actionable "when X, do Y" rules
 *   3. memory_map — topic → grep keywords → files, so the agent's quick
 *                   pass greps the right terms instead of guessing
 *   4. gaps       — known blind spots / unverified facts
 *
 * Failure is safe by construction: any LLM / parse / I/O error returns
 * `success: false`, and the caller keeps the deterministic `summary.md`
 * that `refreshProjections` already wrote. `computeCanonicalHash` gates
 * re-generation via a sidecar, so a busy curation loop never burns tokens
 * re-summarizing unchanged memory.
 */

import * as crypto from 'crypto';
import * as fs from 'fs/promises';
import * as path from 'path';
import { z } from 'zod';

import type { AIClient } from '@duya/ai';

import { chatWithTimeout } from './curation_single_shot';
import { generateSummaryMdLive } from '../../packages/agent/src/memory-state/curation_projection_live';

/** Sidecar file that records the canonical hash the current summary was synthesized from. */
export const SYNTH_HASH_FILENAME = 'summary.md.synth-hash';

const ENTITY_DIRS = ['global/areas', 'global/people', 'global/preferences'] as const;

const DEFAULT_TIMEOUT_MS = 4 * 60_000;

// Per-file cap when assembling the LLM input (a runaway canonical file
// can't blow the prompt). Total input is capped separately.
const MAX_FILE_CHARS = 8_000;
const MAX_TOTAL_CHARS = 48 * 1024;

const MAX_RULES = 10;
const MAX_MAP = 14;
const MAX_GAPS = 6;
// Semantic block size budget. memorySection.ts inlines summary.md into the
// system prompt with a MAX_INLINE_SUMMARY_CHARS cap (raised to 12 KiB to
// make room for this digest); the digest itself should stay well under it
// so the deterministic index below still has room.
const MAX_BLOCK_CHARS = 6_000;

// ---------------------------------------------------------------------------
// Sidecar / hash helpers
// ---------------------------------------------------------------------------

/**
 * sha256 over every canonical file's (relPath + content). Used to decide
 * whether the memory store actually changed since the last synthesis, so
 * Phase 3 only re-runs when there is something new to summarize.
 */
export async function computeCanonicalHash(memoryRoot: string): Promise<string> {
  const hash = crypto.createHash('sha256');
  const parts: string[] = [];
  for (const dir of ENTITY_DIRS) {
    const abs = path.join(memoryRoot, dir);
    let names: string[];
    try {
      names = await fs.readdir(abs);
    } catch {
      continue; // directory not created yet
    }
    for (const name of names.sort()) {
      if (!name.endsWith('.md') || name === 'index.md') continue;
      try {
        const body = await fs.readFile(path.join(abs, name), 'utf8');
        parts.push(`${dir}/${name}\u0000${body}`);
      } catch {
        // unreadable file — skip
      }
    }
  }
  for (const p of parts) hash.update(p);
  return hash.digest('hex');
}

// ---------------------------------------------------------------------------
// LLM contract
// ---------------------------------------------------------------------------

const TopRuleSchema = z.object({
  rule: z.string().min(1).max(500),
  source: z.string().max(200),
  priority: z.number().int().min(1).max(10).optional(),
});

const MemoryMapEntrySchema = z.object({
  topic: z.string().min(1).max(120),
  keywords: z.array(z.string().min(1).max(60)).max(8),
  files: z.array(z.string().min(1).max(200)).max(6),
});

const SemanticSummarySchema = z.object({
  profile: z.string().min(1).max(1_500),
  top_rules: z.array(TopRuleSchema).max(MAX_RULES),
  memory_map: z.array(MemoryMapEntrySchema).max(MAX_MAP),
  gaps: z.array(z.string().min(1).max(400)).max(MAX_GAPS),
});

type SemanticSummary = z.infer<typeof SemanticSummarySchema>;

const SYSTEM_PROMPT = `\
You are the Memory Synthesizer for the DUYA desktop client.

# Your duty

You receive the ENTIRE canonical memory store (every file under
global/{areas,people,preferences}/ plus MEMORY.md, the searchable
registry). Your job is to write the semantic digest that gets inlined
into the agent's system prompt as MEMORY_SUMMARY. The agent reads this
in every single turn, then goes and greps the canonical files for
details. So your digest must answer three questions the raw index cannot:

1. WHO IS THIS USER — synthesized across all files, not per-file.
2. WHAT MATTERS MOST — the handful of rules/context the agent should
   keep in mind even before grepping.
3. HOW TO FIND IT — topic → grep keywords → file map, so the agent's
   quick pass greps the right terms instead of guessing.

# Output contract (STRICT — return ONLY one JSON object)

{
  "profile": "3-6 sentences. A cross-file portrait of the user: what they
              work on, how they work, their preferences and pet peeves,
              recurring workflows. Written as terse assertions.",
  "top_rules": [
    {
      "rule": "Actionable 'When X, do Y' statement. The highest-value
               preferences and procedures, ordered by importance.",
      "source": "global/preferences/canvas.md  (file the rule came from)",
      "priority": 1
    }
  ],
  "memory_map": [
    {
      "topic": "Short topic name (e.g. 'canvas tooling', 'news workflow')",
      "keywords": ["canvas", "fallback", "mcp"],
      "files": ["global/areas/canvas-tool-fallback-protocol.md"]
    }
  ],
  "gaps": [
    "Known blind spot or unverified area, e.g. 'user identity not
     registered', 'hydrology course: no NSE results yet'"
  ]
}

# Hard rules

- Base EVERYTHING on the provided files. Never invent facts, people,
  paths, or preferences that are not in the source content. If a
  dimension is empty in memory, it does not appear.
- "top_rules" must be ACTIONABLE: "When X, do Y", not "User likes Y".
  Prefer explicit preference/correction statements over inferences.
  Cap at 10; if fewer than 3 are clearly high-value, emit fewer — do not
  pad.
- "memory_map" must give grep keywords the agent will actually type
  (project names, tool names, distinctive terms), and map each topic to
  the 1-3 canonical files that hold its details. Cover the main topics;
  cap at 14 entries.
- "gaps" only lists real blind spots visible from the source (missing
  dimensions, retired/superseded items, explicitly unverified facts).
  Cap at 6.
- Keep the whole digest tight: it is inlined into the agent's system
  prompt EVERY turn. The rendered digest must stay under ~4 KB total.
  Terse, high-signal assertions; never restate the index.
- Absolute paths stay verbatim (e.g. E:\\Projects\\duya). Dates as
  YYYY-MM-DD.
- Output ONE JSON object. No markdown code fence, no prose before or
  after.`;

// ---------------------------------------------------------------------------
// Parsing (tolerant, mirrors curation_response_parser.ts)
// ---------------------------------------------------------------------------

/** Strip a ```json ... ``` fence and locate the first balanced JSON object. */
function extractJsonObject(raw: string): string {
  let text = raw.trim();
  const fence = text.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/);
  if (fence) text = fence[1].trim();
  const start = text.indexOf('{');
  if (start === -1) throw new Error('no JSON object found in response');
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') { inString = true; continue; }
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return text.slice(start, i + 1);
    }
  }
  throw new Error('unbalanced JSON object in response');
}

function parseSemanticSummary(raw: string): SemanticSummary {
  const json = extractJsonObject(raw);
  const parsed = JSON.parse(json) as unknown;
  return SemanticSummarySchema.parse(parsed);
}

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

function renderSemanticBlock(s: SemanticSummary): string {
  let rendered = renderSemanticBlockInner(s);
  if (rendered.length > MAX_BLOCK_CHARS) {
    rendered = rendered.slice(0, MAX_BLOCK_CHARS).trimEnd() + '\n...[semantic block truncated]...\n';
  }
  return rendered;
}

function renderSemanticBlockInner(s: SemanticSummary): string {
  const lines: string[] = [];

  lines.push('## Who is this user');
  lines.push('');
  lines.push(s.profile.trim());
  lines.push('');

  if (s.top_rules.length > 0) {
    lines.push('## Rules that matter');
    lines.push('');
    const sorted = [...s.top_rules].sort(
      (a, b) => (a.priority ?? 99) - (b.priority ?? 99),
    );
    sorted.forEach((r, i) => {
      lines.push(`${i + 1}. **${r.rule}** — \`${r.source}\``);
    });
    lines.push('');
  }

  if (s.memory_map.length > 0) {
    lines.push('## How to find things');
    lines.push('');
    for (const e of s.memory_map) {
      const kw = e.keywords.join(', ');
      const files = e.files.join(', ');
      lines.push(`- **${e.topic}**: keywords: \`${kw}\` → ${files}`);
    }
    lines.push('');
  }

  if (s.gaps.length > 0) {
    lines.push('## Blind spots');
    lines.push('');
    for (const g of s.gaps) lines.push(`- ${g}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export interface SynthesizeSummaryOpts {
  memoryRoot: string;
  llmClient: AIClient;
  /** Wall-clock budget for the LLM call (ms). Default 4 minutes. */
  timeoutMs?: number;
  /** Override the system prompt (test hook). */
  systemPrompt?: string;
}

export interface SynthesizeSummaryResult {
  success: boolean;
  /**
   * Full `summary.md` content. On `success: false` this is the
   * deterministic index fallback (from `generateSummaryMdLive`), so
   * the caller can always write it — Phase 2 no longer owns summary.md.
   */
  content: string;
  error?: string;
}

/**
 * Deterministic fallback when LLM synthesis fails. Guarantees that
 * summary.md is never empty — Phase 2 no longer writes it.
 */
function deterministicFallback(memoryRoot: string): string {
  try {
    const index = generateSummaryMdLive(memoryRoot);
    return index || '# Memory summary\n\n_(empty store)_\n';
  } catch {
    return '# Memory summary\n\n_(empty store)_\n';
  }
}

/**
 * Assemble the LLM input: every canonical file + MEMORY.md, capped.
 */
async function assembleInput(memoryRoot: string): Promise<string> {
  const chunks: Array<{ file: string; content: string }> = [];
  let total = 0;

  for (const dir of ENTITY_DIRS) {
    const abs = path.join(memoryRoot, dir);
    let names: string[];
    try {
      names = await fs.readdir(abs);
    } catch {
      continue;
    }
    for (const name of names.sort()) {
      if (!name.endsWith('.md') || name === 'index.md') continue;
      try {
        const body = await fs.readFile(path.join(abs, name), 'utf8');
        const capped = body.length > MAX_FILE_CHARS
          ? body.slice(0, MAX_FILE_CHARS) + '\n...[truncated]...'
          : body;
        chunks.push({ file: `${dir}/${name}`, content: capped });
        total += capped.length;
      } catch {
        // unreadable — skip
      }
    }
  }

  const memoryPath = path.join(memoryRoot, 'MEMORY.md');
  try {
    const body = await fs.readFile(memoryPath, 'utf8');
    const capped = body.length > 16_000 ? body.slice(0, 16_000) + '\n...[truncated]...' : body;
    chunks.push({ file: 'MEMORY.md', content: capped });
    total += capped.length;
  } catch {
    // MEMORY.md missing — fine, canonical files are the source of truth
  }

  // If we still overflow, drop the largest chunks until we fit.
  if (total > MAX_TOTAL_CHARS) {
    chunks.sort((a, b) => b.content.length - a.content.length);
    let running = 0;
    const kept: Array<{ file: string; content: string }> = [];
    for (const c of chunks) {
      if (running + c.content.length > MAX_TOTAL_CHARS) continue;
      kept.push(c);
      running += c.content.length;
    }
    chunks.splice(0, chunks.length, ...kept);
  }

  return JSON.stringify({ files: chunks }, null, 2);
}

/**
 * Synthesize a semantic `summary.md`. Never throws — always returns a
 * `content` (semantic digest on success, deterministic index fallback on
 * failure) so the caller can write summary.md unconditionally.
 */
export async function synthesizeSummary(
  opts: SynthesizeSummaryOpts,
): Promise<SynthesizeSummaryResult> {
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const systemPrompt = opts.systemPrompt ?? SYSTEM_PROMPT;
  const fallback = (error: string): SynthesizeSummaryResult => ({
    success: false,
    content: deterministicFallback(opts.memoryRoot),
    error,
  });

  let userPrompt: string;
  try {
    userPrompt = await assembleInput(opts.memoryRoot);
  } catch (err) {
    return fallback(
      `input assembly failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  let raw: string;
  try {
    const messages: Parameters<AIClient['chat']>[0] = [
      { role: 'user', content: userPrompt },
    ];
    const chatResult = await chatWithTimeout(
      opts.llmClient,
      messages,
      { systemPrompt },
      timeoutMs,
    );
    raw = chatResult.content ?? '';
    if (raw.trim().length === 0) {
      return fallback('empty LLM response');
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    const timedOut = (err as Error).name === 'AbortError' || /aborted/i.test(msg);
    return fallback(
      timedOut ? `llm call timed out after ${timeoutMs}ms` : `llm call failed: ${msg}`,
    );
  }

  let semantic: SemanticSummary;
  try {
    semantic = parseSemanticSummary(raw);
  } catch (err) {
    return fallback(
      `parse failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  try {
    const block = renderSemanticBlock(semantic);
    const index = generateSummaryMdLive(opts.memoryRoot);
    // Insert the semantic block right before the deterministic index's
    // "## Essentials" section so the routing table stays intact below it.
    const marker = '## Essentials';
    const idx = index.indexOf(marker);
    const content =
      idx >= 0
        ? index.slice(0, idx) + block + '\n\n' + index.slice(idx)
        : block + '\n\n' + index;
    return { success: true, content };
  } catch (err) {
    return fallback(
      `render failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}
