/**
 * Plan 587 R2.1 — the run-identity shim in the legacy agent.
 *
 * ## What this pins
 *
 * `DuyaAgent.streamChat` used to call `crypto.randomUUID()` inline and use it as
 * the run identity for mailbox claim attribution. R2.1 puts the canonical run id
 * on `chat:start`, so the agent must USE that value rather than mint a second
 * one — a second identity is precisely what contract §B forbids ("`runId` is
 * generated by the CP/start entry and runs through the worker command").
 *
 * The extraction into `run-identity.ts` is what makes this testable at all: the
 * call site is inside a 3,500-line generator with no seam, so a source-level
 * assertion would be the only alternative, and a source-level assertion cannot
 * tell a wired id from a copied one.
 *
 * ## The shim's exit condition
 *
 * `canonical: false` exists only because the non-Desktop producers still issue
 * `chat:start` without a run id, and they are registered for H8 (see
 * `NON_DESKTOP_CONSUMERS` in `run-orchestrator.ts`). When all of them supply
 * one, `canonical: false` stops occurring and the fallback can be deleted. This
 * test is what makes that countable.
 */

import { describe, expect, it } from 'vitest';
import { resolveTurnRunId } from '../../../src/agent/run-identity.js';

describe('resolveTurnRunId', () => {
  it('uses the canonical id verbatim — the same string, not an alias', () => {
    // "Alias" is the failure mode to rule out: a mapping between the canonical
    // id and a second one is still two identities, and the mailbox would
    // attribute a claim to something no `runs` row knows about.
    const canonical = '2f6a9c1e-0b7d-4a51-9d3e-8c1f0a5b2d40';
    const resolved = resolveTurnRunId(canonical);
    expect(resolved.runId).toBe(canonical);
    expect(resolved.canonical).toBe(true);
  });

  it('mints and REPORTS a non-canonical id when the producer sent none', () => {
    // Registered for H8, not migrated in this slice. The fallback is honest
    // about itself rather than silent, so "the legacy agent minted its own id"
    // is a countable event and not something a reviewer has to notice.
    const resolved = resolveTurnRunId(undefined);
    expect(resolved.canonical).toBe(false);
    expect(resolved.runId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  });

  it('treats an empty string as absent rather than as an id', () => {
    // A producer that sends `runId: ''` has told us nothing. Minting a real one
    // BEHIND it would produce two identities for one turn and leave the empty
    // one on the durable record.
    expect(resolveTurnRunId('').canonical).toBe(false);
    expect(resolveTurnRunId('').runId).not.toBe('');
  });

  it('never hands the same minted id to two turns', () => {
    // Two turns sharing a fallback id would make their mailbox claims collide,
    // which is the same class of bug as the canonical path is meant to remove.
    const first = resolveTurnRunId(undefined);
    const second = resolveTurnRunId(undefined);
    expect(first.runId).not.toBe(second.runId);
  });
});
