"use client";

import { useSyncExternalStore } from "react";

/**
 * Tiny pub-sub for the latest recap text. The recap is generated by the
 * main-process RecapService (Plan 65) and arrives in the renderer via
 * `recap:result` IPC. ChatView is the publisher (it owns the IPC
 * subscription); TaskDrawer is the consumer (it renders the recap inline
 * with the task list). They live in different subtrees — same problem the
 * task-drawer-store solves for the open/close flag — so we mirror that
 * pattern with a hand-rolled useSyncExternalStore rather than dragging in
 * a global Zustand store for one piece of state.
 */
export interface RecapState {
  text: string | null;
  receivedAt: number | null;
  sessionId: string | null;
}

const EMPTY: RecapState = { text: null, receivedAt: null, sessionId: null };

let state: RecapState = EMPTY;
const listeners = new Set<() => void>();

function emit(): void {
  for (const fn of listeners) fn();
}

export function getRecap(): RecapState {
  return state;
}

export function setRecap(next: RecapState): void {
  // Skip the no-op update so subscribers don't re-render on identical state.
  if (
    state.text === next.text &&
    state.receivedAt === next.receivedAt &&
    state.sessionId === next.sessionId
  ) {
    return;
  }
  state = next;
  emit();
}

export function clearRecap(): void {
  if (state === EMPTY) return;
  state = EMPTY;
  emit();
}

export function subscribeRecap(fn: () => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

export function useRecap(): RecapState {
  return useSyncExternalStore(subscribeRecap, getRecap, getRecap);
}