"use client";

/**
 * code-review-code-viewer.tsx — ZCode-style file preview with per-line
 * comments, built on `@pierre/diffs`'s React `File` component.
 *
 * The library renders the code inside a `diffs-container` custom element
 * (Shadow DOM) and projects React children back into the page DOM via
 * `<div slot=...>` — annotation cards stay in the light DOM, so duya's
 * global styles apply to them directly. What lives inside the Shadow DOM
 * (line rows, gutter utility button) is only reachable through the
 * `unsafeCSS` option and `data-*` attributes.
 *
 * Interaction model (all provided by the library's InteractionManager):
 *   - hover a line → gutter "+" button (positioned right via unsafeCSS)
 *   - click / drag the "+" or click lines → line range selection
 *   - selection end → inline draft card under the last selected line
 *   - submitted comments render as inline cards under their anchor line
 */

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
} from "react";
import { TrashIcon } from "@/components/icons";
import { Button } from "@/components/ui/Button";
import {
  File,
  type FileContents,
  type FileOptions,
  type LineAnnotation,
  type SelectedLineRange,
  type SupportedLanguages,
} from "@pierre/diffs/react";

/** Minimal comment shape the viewer needs (see CodeComment in the store). */
export interface CodeViewerComment {
  id: string;
  startLine: number;
  endLine: number;
  comment: string;
}

export interface CodeViewerLabels {
  addCommentTooltip: string;
  commentPlaceholder: string;
  submitComment: string;
  cancelComment: string;
  deleteComment: string;
  commentLine: string;
  commentRange: string;
}

const DEFAULT_LABELS: CodeViewerLabels = {
  addCommentTooltip: "点击或拖拽行添加评论",
  commentPlaceholder: "写下评论…",
  submitComment: "添加评论",
  cancelComment: "取消",
  deleteComment: "删除评论",
  commentLine: "第 {line} 行",
  commentRange: "第 {startLine}-{endLine} 行",
};

type CodeCommentRange = { startLine: number; endLine: number };

type AnnotationMetadata =
  | { kind: "comment"; comment: CodeViewerComment }
  | { kind: "draft"; range: CodeCommentRange };

type CodeViewerStyle = CSSProperties & {
  "--code-comment-add-tooltip"?: string;
  "--diffs-bg"?: string;
  "--diffs-light-bg"?: string;
  "--diffs-dark-bg"?: string;
  "--diffs-font-family"?: string;
  "--diffs-font-size"?: string;
};

/**
 * Gutter utility tweaks injected into the Shadow DOM: move the built-in
 * "+" button to the right edge of the gutter and give it a CSS-only
 * tooltip (the button itself is generated by the library's
 * InteractionManager; we only style it, never touch its pointer events,
 * so multi-line drag selection keeps working).
 */
const GUTTER_UNSAFE_CSS = [
  "[data-gutter-utility-slot]{left:auto;right:4px;justify-content:flex-end;align-items:center;}",
  "[data-utility-button]{margin-left:0;margin-right:0;}",
  "@media (hover:hover) and (pointer:fine){",
  "[data-utility-button]::after{content:var(--code-comment-add-tooltip);position:absolute;left:calc(100% + 6px);top:50%;transform:translateY(-50%);max-width:16rem;white-space:nowrap;pointer-events:none;opacity:0;z-index:5;border:1px solid var(--border-strong);border-radius:8px;background:var(--surface-solid);color:var(--text);padding:4px 8px;font-size:12px;line-height:16px;box-shadow:0 4px 12px rgb(0 0 0 / 0.14);}",
  "[data-utility-button]:hover::after,[data-utility-button]:focus-visible::after{opacity:1;}",
  "}",
].join("");

function hashCodeContent(code: string): string {
  let hash = 5381;
  for (let index = 0; index < code.length; index += 1) {
    hash = (hash * 33) ^ code.charCodeAt(index);
  }
  return (hash >>> 0).toString(36);
}

function isApplePlatform(platformInfo?: KeyboardShortcutPlatformInfo): boolean {
  const source = platformInfo
    ? `${platformInfo.platform ?? ""} ${platformInfo.userAgent ?? ""}`
    : typeof navigator === "undefined"
      ? ""
      : `${navigator.platform || ""} ${navigator.userAgent || ""}`;
  return /mac|iphone|ipad|ipod/i.test(source);
}

export interface KeyboardShortcutPlatformInfo {
  platform?: string;
  userAgent?: string;
}

export function isCommentSubmitShortcut(
  event: Pick<ReactKeyboardEvent<HTMLTextAreaElement>, "ctrlKey" | "key" | "metaKey">,
  platformInfo?: KeyboardShortcutPlatformInfo,
): boolean {
  if (event.key !== "Enter") return false;
  return isApplePlatform(platformInfo) ? event.metaKey : event.ctrlKey;
}

function normalizeRange(range: CodeCommentRange): CodeCommentRange {
  return {
    startLine: Math.min(range.startLine, range.endLine),
    endLine: Math.max(range.startLine, range.endLine),
  };
}

function selectionToCommentRange(
  range: SelectedLineRange,
  firstLineNumber: number,
): CodeCommentRange {
  return normalizeRange({
    startLine: firstLineNumber + range.start - 1,
    endLine: firstLineNumber + range.end - 1,
  });
}

function commentRangeToSelection(
  range: CodeCommentRange,
  firstLineNumber: number,
): SelectedLineRange {
  const normalized = normalizeRange(range);
  return {
    start: normalized.startLine - firstLineNumber + 1,
    end: normalized.endLine - firstLineNumber + 1,
  };
}

function getTextForLineRange(code: string, firstLineNumber: number, range: CodeCommentRange) {
  const lines = code.split("\n");
  const normalized = normalizeRange(range);
  const startIndex = Math.max(normalized.startLine - firstLineNumber, 0);
  const endIndex = Math.min(normalized.endLine - firstLineNumber, lines.length - 1);
  if (startIndex > endIndex) return "";
  return lines.slice(startIndex, endIndex + 1).join("\n");
}

function formatCommentRange(labels: CodeViewerLabels, range: CodeCommentRange) {
  const normalized = normalizeRange(range);
  if (normalized.startLine === normalized.endLine) {
    return labels.commentLine.replaceAll("{line}", String(normalized.startLine));
  }
  return labels.commentRange
    .replaceAll("{startLine}", String(normalized.startLine))
    .replaceAll("{endLine}", String(normalized.endLine));
}

/** Shiki bundled languages we are willing to highlight; anything else renders as text. */
const SHIKI_LANGUAGE_BY_EXTENSION: Record<string, string> = {
  ts: "typescript", tsx: "tsx", mts: "typescript", cts: "typescript",
  js: "javascript", jsx: "jsx", mjs: "javascript", cjs: "javascript",
  json: "json", jsonc: "jsonc", json5: "jsonc",
  css: "css", scss: "scss", less: "less",
  html: "html", htm: "html", vue: "vue", svelte: "svelte",
  md: "markdown", mdx: "mdx",
  py: "python", pyi: "python",
  rs: "rust", go: "go", java: "java", kt: "kotlin", kts: "kotlin",
  c: "c", h: "c", cpp: "cpp", cc: "cpp", hpp: "cpp", hxx: "cpp",
  cs: "csharp", rb: "ruby", php: "php", swift: "swift",
  sh: "shellscript", bash: "shellscript", zsh: "shellscript",
  ps1: "powershell", psm1: "powershell",
  yaml: "yaml", yml: "yaml", toml: "toml",
  sql: "sql", lua: "lua", graphql: "graphql", gql: "graphql",
  ini: "ini", env: "ini", dockerfile: "dockerfile",
};

export function extensionToHighlightLanguage(path: string): string {
  const match = path.match(/\.([A-Za-z0-9]+)$/);
  if (!match) return "text";
  return SHIKI_LANGUAGE_BY_EXTENSION[match[1].toLowerCase()] ?? "text";
}

interface CommentDraftProps {
  range: CodeCommentRange;
  labels: CodeViewerLabels;
  value: string;
  onValueChange: (value: string) => void;
  onSubmit: () => void;
  onCancel: () => void;
}

function CommentDraft({ range, labels, value, onValueChange, onSubmit, onCancel }: CommentDraftProps) {
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    const frameId = requestAnimationFrame(() => {
      textareaRef.current?.focus();
    });
    return () => cancelAnimationFrame(frameId);
  }, []);

  return (
    <div className="code-review-comment-card">
      <div className="code-review-comment-card-range">{formatCommentRange(labels, range)}</div>
      <textarea
        ref={textareaRef}
        value={value}
        onChange={(event) => onValueChange(event.currentTarget.value)}
        onKeyDown={(event) => {
          if (isCommentSubmitShortcut(event)) {
            event.preventDefault();
            onSubmit();
            return;
          }
          if (event.key !== "Escape") return;
          event.preventDefault();
          onCancel();
        }}
        placeholder={labels.commentPlaceholder}
        className="code-review-comment-card-input"
        rows={3}
      />
      <div className="code-review-comment-card-actions">
        <Button type="button" variant="ghost" size="sm" onClick={onCancel}>
          {labels.cancelComment}
        </Button>
        <Button type="button" size="sm" onClick={onSubmit}>
          {labels.submitComment}
        </Button>
      </div>
    </div>
  );
}

function CommentCard({
  comment,
  labels,
  showRange,
  onDelete,
}: {
  comment: CodeViewerComment;
  labels: CodeViewerLabels;
  showRange?: boolean;
  onDelete?: (commentId: string) => void;
}) {
  return (
    <div className="code-review-comment-card" data-code-comment-id={comment.id}>
      {showRange ? (
        <div className="code-review-comment-card-range">
          {formatCommentRange(labels, comment)}
        </div>
      ) : null}
      {comment.comment.trim() ? (
        <div className="code-review-comment-card-body">{comment.comment}</div>
      ) : null}
      {onDelete ? (
        <div className="code-review-comment-card-actions">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            title={labels.deleteComment}
            aria-label={labels.deleteComment}
            onClick={() => onDelete(comment.id)}
          >
            <TrashIcon size={13} aria-hidden="true" />
            {labels.deleteComment}
          </Button>
        </div>
      ) : null}
    </div>
  );
}

export interface CodeViewerProps {
  code: string;
  /** File name (basename) — used by the library for language inference fallback. */
  fileName: string;
  highlightLanguage?: string;
  showLineNumbers?: boolean;
  wrapLongLines?: boolean;
  fontSizePx?: number;
  firstLineNumber?: number;
  darkMode?: boolean;
  comments?: readonly CodeViewerComment[];
  enableComments?: boolean;
  labels?: Partial<CodeViewerLabels>;
  onSubmitComment?: (params: { range: CodeCommentRange; selectedText: string; comment: string }) => void;
  onDeleteComment?: (commentId: string) => void;
  onScrollCapture?: (node: HTMLDivElement | null) => void;
  className?: string;
}

export function CodeViewer({
  code,
  fileName,
  highlightLanguage,
  showLineNumbers = true,
  wrapLongLines = false,
  fontSizePx = 12,
  firstLineNumber = 1,
  darkMode = false,
  comments = [],
  enableComments = false,
  labels: labelOverrides,
  onSubmitComment,
  onDeleteComment,
  onScrollCapture,
  className,
}: CodeViewerProps) {
  const viewerRef = useRef<HTMLDivElement | null>(null);
  const [draftRange, setDraftRange] = useState<CodeCommentRange | null>(null);
  const [draftText, setDraftText] = useState("");
  const labels = useMemo(() => ({ ...DEFAULT_LABELS, ...labelOverrides }), [labelOverrides]);
  const canCreateComment = Boolean(onSubmitComment) && enableComments;

  const language = (highlightLanguage ?? extensionToHighlightLanguage(fileName)) as SupportedLanguages;
  const file = useMemo<FileContents>(
    () => ({
      name: fileName,
      contents: code,
      lang: language,
      // cacheKey participates in the library's highlight token cache; it must
      // change whenever content OR theme changes, otherwise a theme flip
      // reuses stale tokens until the next content edit.
      cacheKey: `${darkMode ? "dark" : "light"}:${fileName}:${language}:${code.length}:${hashCodeContent(code)}`,
    }),
    [code, darkMode, fileName, language],
  );

  const annotations = useMemo<LineAnnotation<AnnotationMetadata>[]>(() => {
    const list: LineAnnotation<AnnotationMetadata>[] = [];
    for (const comment of comments) {
      const lineNumber = normalizeRange(comment).endLine - firstLineNumber + 1;
      if (lineNumber < 1) continue;
      list.push({ lineNumber, metadata: { kind: "comment", comment } });
    }
    if (canCreateComment && draftRange) {
      list.push({
        lineNumber: normalizeRange(draftRange).endLine - firstLineNumber + 1,
        metadata: { kind: "draft", range: draftRange },
      });
    }
    return list;
  }, [canCreateComment, comments, draftRange, firstLineNumber]);

  const selectedLines = useMemo<SelectedLineRange | null>(
    () => (canCreateComment && draftRange ? commentRangeToSelection(draftRange, firstLineNumber) : null),
    [canCreateComment, draftRange, firstLineNumber],
  );

  const handleLineSelectionEnd = useCallback(
    (range: SelectedLineRange | null) => {
      if (!canCreateComment || !range) return;
      setDraftRange(selectionToCommentRange(range, firstLineNumber));
      setDraftText("");
    },
    [canCreateComment, firstLineNumber],
  );

  const handleGutterUtilityClick = useCallback(
    (range: SelectedLineRange) => {
      if (!canCreateComment) return;
      setDraftRange(selectionToCommentRange(range, firstLineNumber));
      setDraftText("");
    },
    [canCreateComment, firstLineNumber],
  );

  const handleSubmitDraft = useCallback(() => {
    if (!draftRange) return;
    const selectedText = getTextForLineRange(code, firstLineNumber, draftRange);
    if (!selectedText.trim()) return;
    onSubmitComment?.({
      range: normalizeRange(draftRange),
      selectedText,
      comment: draftText.trim(),
    });
    setDraftRange(null);
    setDraftText("");
  }, [code, draftRange, draftText, firstLineNumber, onSubmitComment]);

  // The library generates the gutter "+" buttons inside the Shadow DOM without
  // title/aria-label. Patch them (rAF-throttled, MutationObserver-driven) purely
  // on the accessibility surface — never intercept pointer events, which would
  // break the built-in multi-line drag selection.
  useEffect(() => {
    if (!canCreateComment || !viewerRef.current) return;
    const root = viewerRef.current;
    const observers: MutationObserver[] = [];
    const observedRoots = new WeakSet<Node>();
    let animationFrame = 0;

    const patch = () => {
      for (const button of root.querySelectorAll<HTMLButtonElement>("button[data-utility-button]")) {
        button.title = labels.addCommentTooltip;
        button.setAttribute("aria-label", labels.addCommentTooltip);
      }
      const walk = (node: ParentNode) => {
        for (const element of node.querySelectorAll<HTMLElement>("*")) {
          if (!element.shadowRoot) continue;
          if (!observedRoots.has(element.shadowRoot)) {
            observedRoots.add(element.shadowRoot);
            const observer = new MutationObserver(schedulePatch);
            observer.observe(element.shadowRoot, { childList: true, subtree: true });
            observers.push(observer);
          }
          for (const button of element.shadowRoot.querySelectorAll<HTMLButtonElement>("button[data-utility-button]")) {
            button.title = labels.addCommentTooltip;
            button.setAttribute("aria-label", labels.addCommentTooltip);
          }
          walk(element.shadowRoot);
        }
      };
      walk(root);
    };

    function schedulePatch() {
      if (animationFrame) return;
      animationFrame = window.requestAnimationFrame(() => {
        animationFrame = 0;
        patch();
      });
    }

    observedRoots.add(root);
    const rootObserver = new MutationObserver(schedulePatch);
    rootObserver.observe(root, { childList: true, subtree: true });
    observers.push(rootObserver);
    schedulePatch();

    return () => {
      if (animationFrame) window.cancelAnimationFrame(animationFrame);
      for (const observer of observers) observer.disconnect();
    };
  }, [canCreateComment, labels.addCommentTooltip]);

  const options = useMemo<FileOptions<AnnotationMetadata, undefined>>(
    () => ({
      disableFileHeader: true,
      disableLineNumbers: !showLineNumbers,
      overflow: wrapLongLines ? "wrap" : "scroll",
      themeType: darkMode ? "dark" : "light",
      enableLineSelection: canCreateComment,
      enableGutterUtility: canCreateComment,
      lineHoverHighlight: canCreateComment ? "both" : "disabled",
      onLineSelectionEnd: canCreateComment ? handleLineSelectionEnd : undefined,
      onGutterUtilityClick: canCreateComment ? handleGutterUtilityClick : undefined,
      unsafeCSS: GUTTER_UNSAFE_CSS,
    }),
    [
      canCreateComment,
      darkMode,
      handleGutterUtilityClick,
      handleLineSelectionEnd,
      showLineNumbers,
      wrapLongLines,
    ],
  );

  const viewerStyle = useMemo<CodeViewerStyle>(
    () => ({
      // The library's tokens rely on color-scheme / light-dark(); an explicit
      // value keeps code text legible when the app theme and the OS preference
      // disagree (e.g. dark app on a light-preference system).
      colorScheme: darkMode ? "dark" : "light",
      "--diffs-bg": "var(--main-bg)",
      "--diffs-light-bg": "var(--main-bg)",
      "--diffs-dark-bg": "var(--main-bg)",
      // Explicit mono font: the library's Shadow-DOM fallback lands Chinese
      // comments in a serif face on Windows unless overridden.
      "--diffs-font-family": 'var(--font-mono, "Cascadia Code", Consolas, monospace)',
      "--diffs-font-size": `${fontSizePx}px`,
      "--code-comment-add-tooltip": JSON.stringify(
        canCreateComment ? labels.addCommentTooltip : "",
      ),
    }),
    [canCreateComment, darkMode, fontSizePx, labels.addCommentTooltip],
  );

  return (
    <div
      ref={(node) => {
        viewerRef.current = node;
        onScrollCapture?.(node);
      }}
      className={`code-review-code-viewer${className ? ` ${className}` : ""}`}
      style={viewerStyle}
    >
      <File
        key={file.cacheKey}
        file={file}
        options={options}
        lineAnnotations={annotations}
        selectedLines={selectedLines}
        className="code-review-code-viewer-file"
        renderAnnotation={(annotation) => {
          const metadata = annotation.metadata;
          if (!metadata) return null;
          return metadata.kind === "draft" ? (
            <CommentDraft
              range={metadata.range}
              labels={labels}
              value={draftText}
              onValueChange={setDraftText}
              onSubmit={handleSubmitDraft}
              onCancel={() => {
                setDraftRange(null);
                setDraftText("");
              }}
            />
          ) : (
            <CommentCard comment={metadata.comment} labels={labels} onDelete={onDeleteComment} />
          );
        }}
      />
    </div>
  );
}
