/**
 * botRoster — data prepare step for `bot/roster.hbs` (Plan 474 P2.3 +
 * Plan 492 P1.2 upgrade).
 *
 * Plan 558 split: the *content* lives in
 * `buildAgentMessagingSystemPrompt` (agent/dm/wake-prompt.ts); this
 * module maps `BotPromptContext` to the template-friendly
 * `rosterContract` + `prefixMore` + `moreCount` fields the template
 * consumes. The template stays one line — most of the section body is
 * the contract text generated by `buildAgentMessagingSystemPrompt`.
 *
 * Returns null when the context carries no directory and no groups —
 * matches the pre-migration `renderBotRoster` guard.
 *
 * Single exit point for the inter-agent messaging contract (Plan 492
 * D4): the section IS the contract text plus the teammate directory
 * read from `[agents.<id>]` in config.toml (Plan 424 read side). The
 * commsRules section deliberately no longer repeats agent-to-agent
 * rules — this is the one place they live (grok also renders contract +
 * directory from one spot).
 */

import type { BotPromptContext } from './framework.js'
import { buildAgentMessagingSystemPrompt } from '../../agent/dm/wake-prompt.js'
import { identityHbsSentinel, makeBotTemplateHbs } from './hbsCompat.js'

/** Cap: directory is bounded to keep the section short (grok caps at 40). */
export const BOT_ROSTER_MAX_ENTRIES = 40

export interface BotRosterContext extends BotPromptContext {
  rosterContract: string
  prefixMore: boolean
  moreCount: number
}

export function prepareBotRosterContext(ctx: BotPromptContext): BotRosterContext | null {
  const entries = ctx.agentDirectory
  const groups = ctx.agentGroups
  if ((!entries || entries.length === 0) && (!groups || groups.length === 0)) return null

  const shown = (entries ?? []).slice(0, BOT_ROSTER_MAX_ENTRIES)
  const rosterContract = buildAgentMessagingSystemPrompt(
    shown.map((entry) => ({
      id: entry.id,
      name: entry.name || entry.id,
      description: entry.description,
    })),
    {
      groups: (groups ?? []).map((group) => ({
        id: group.id,
        name: group.name,
        members: group.members.map((member) => ({
          id: member.id,
          name: member.name || member.id,
          description: member.description,
        })),
      })),
    },
  )
  return {
    ...ctx,
    rosterContract,
    prefixMore: !!(entries && entries.length > BOT_ROSTER_MAX_ENTRIES),
    moreCount: (entries?.length ?? 0) - BOT_ROSTER_MAX_ENTRIES,
  }
}

/**
 * @deprecated Use the catalog + `BotPromptAssembly.render()`.
 *   Sync wrapper kept for legacy tests that asserted on the raw roster
 *   body. Mirrors the pre-plan-558 `renderBotRoster` semantics.
 */
export function renderBotRoster(ctx: BotPromptContext): string | null {
  const prepared = prepareBotRosterContext(ctx)
  if (!prepared) return null
  const out = makeBotTemplateHbs().renderStaticTemplate(
    'bot/roster.hbs',
    identityHbsSentinel,
    { ...prepared },
  )
  return out === '' ? null : out
}