"use client";

import {
  ArrowUpRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  LightningIcon,
  MagicWandIcon,
  SparkleIcon,
  ClockCounterClockwiseIcon,
  PlayCircleIcon,
  RepeatIcon,
  GearSixIcon,
  KeyIcon,
  MonitorIcon,
  PlugIcon,
  ShieldCheckIcon,
  CodeIcon,
  DatabaseIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  DotsThreeIcon,
  MagnifyingGlassIcon,
  NotePencilIcon,
  SquaresFourIcon,
  SunIcon,
  MoonIcon,
  MoonStarsIcon,
  PaperPlaneRightIcon,
  PaperPlaneTiltIcon,
  StopIcon,
  UserIcon,
  HouseIcon,
  CpuIcon,
  CubeIcon,
  SpinnerGapIcon,
  InfoIcon,
  ShieldIcon,
  XIcon,
  CommandIcon,
  PlusIcon,
  MinusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  MicrophoneIcon,
  ArrowUpIcon,
  TerminalIcon,
  QuestionIcon,
  EraserIcon,
  ChartLineIcon,
  ChartBarIcon,
  GlobeSimpleIcon,
  CopyIcon,
  CheckIcon,
  CaretUpIcon,
  ChatCircleIcon,
  FileIcon,
  WrenchIcon,
  CheckCircleIcon,
  XCircleIcon,
  FolderIcon,
  FolderOpenIcon,
  GitBranchIcon,
  ArchiveIcon,
  EyeIcon,
  EyeSlashIcon,
  CircleIcon,
  CircleNotchIcon,
  TrashIcon,
  FileTextIcon,
  WarningIcon,
  ProhibitIcon,
  HardDrivesIcon,
  PowerIcon,
  ChatCircleTextIcon,
  LightbulbIcon,
  ImageIcon,
  CursorClickIcon,
  CookieIcon,
  At as AtSignIcon,
  MagnifyingGlassIcon as SearchIcon,
  CaretDownIcon as ChevronDownIcon,
  CaretUpIcon as ChevronUpIcon,
  StarIcon,
  // Bridge icons
  WifiHighIcon,
  TelegramLogoIcon,
  ArrowsClockwiseIcon,
  // Browser extension icons
  GoogleChromeLogoIcon,
  ArrowSquareOutIcon,
  // Attachment menu icons
  PaperclipIcon,
  GithubLogoIcon,
  FeatherIcon,
  DownloadSimpleIcon,
} from "@phosphor-icons/react";

// Tabler Icons - Agent icons & Channel icons
import {
  IconCardboards,
  IconBrain,
  IconCode,
  IconMessageCircle,
  IconRobot,
} from "@tabler/icons-react";

// Re-export all icons
export {
  ArrowUpRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  LightningIcon,
  MagicWandIcon,
  SparkleIcon,
  ClockCounterClockwiseIcon,
  PlayCircleIcon,
  RepeatIcon,
  GearSixIcon,
  KeyIcon,
  MonitorIcon,
  PlugIcon,
  ShieldCheckIcon,
  CodeIcon,
  DatabaseIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  DotsThreeIcon,
  MagnifyingGlassIcon,
  NotePencilIcon,
  SquaresFourIcon,
  SunIcon,
  MoonIcon,
  MoonStarsIcon,
  PaperPlaneRightIcon,
  PaperPlaneTiltIcon,
  StopIcon,
  UserIcon,
  HouseIcon,
  CpuIcon,
  CubeIcon,
  SpinnerGapIcon,
  InfoIcon,
  ShieldIcon,
  XIcon,
  CommandIcon,
  PlusIcon,
  MinusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  MicrophoneIcon,
  ArrowUpIcon,
  TerminalIcon,
  QuestionIcon,
  EraserIcon,
  ChartLineIcon,
  ChartBarIcon,
  GlobeSimpleIcon,
  CopyIcon,
  CheckIcon,
  CaretUpIcon,
  ChatCircleIcon,
  FileIcon,
  WrenchIcon,
  CheckCircleIcon,
  XCircleIcon,
  FolderIcon,
  FolderOpenIcon,
  GitBranchIcon,
  ArchiveIcon,
  EyeIcon,
  EyeSlashIcon,
  CircleIcon,
  CircleNotchIcon,
  TrashIcon,
  FileTextIcon,
  WarningIcon,
  ProhibitIcon,
  HardDrivesIcon,
  PowerIcon,
  ChatCircleTextIcon,
  LightbulbIcon,
  ImageIcon,
  CursorClickIcon,
  CookieIcon,
  AtSignIcon,
  SearchIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  StarIcon,
  // Bridge icons
  WifiHighIcon,
  TelegramLogoIcon,
  ArrowsClockwiseIcon,
  // Browser extension icons
  GoogleChromeLogoIcon as ChromeIcon,
  ArrowSquareOutIcon as ExternalLinkIcon,
  // Attachment menu icons
  PaperclipIcon,
  GithubLogoIcon,
  FeatherIcon,
  DownloadSimpleIcon,
  // Tabler Icons - Agent icons (using IconCardboards as main agent icon)
  IconCardboards as RobotIcon,
  IconBrain as BrainIcon,
  IconCode as TablerCodeIcon,
  IconMessageCircle as TablerMessageCircleIcon,
  IconRobot as TablerRobotIcon,
  // Tabler Icons - Channel icons
  IconMessageCircle as ChannelIcon,
};

// Aliases for backward compatibility
export const ServerIcon = HardDrivesIcon;
export const MessageCircleIcon = ChatCircleTextIcon;
export const ZapIcon = LightningIcon;
export const PowerOffIcon = PowerIcon;

// SpinnerIcon is an alias for CircleNotchIcon
export const SpinnerIcon = CircleNotchIcon;

// DocumentTextIcon is an alias for FileTextIcon
export const DocumentTextIcon = FileTextIcon;
