// One-shot helper: read all 4 module READMEs and emit escaped TS template
// literal fragments. Run from project root with `node scripts/inline-modules.mjs`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const MODULES_DIR = 'packages/agent/src/modules';
const NAMES = ['diagram', 'mockup', 'chart', 'interactive'];

function escape(content) {
  // Order matters: backslash first, then backtick, then ${ so we end up with
  // a raw string that round-trips through a TS template literal unchanged.
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

const blocks = NAMES.map(n => {
  const path = join(MODULES_DIR, n, 'README.md');
  const content = readFileSync(path, 'utf8');
  return `export const INLINE_${n.toUpperCase()} = \`${escape(content)}\`;`;
}).join('\n\n');

const out = `// AUTO-GENERATED by scripts/inline-modules.mjs — DO NOT EDIT BY HAND.
// Source files: packages/agent/src/modules/<name>/README.md
// Regenerate with: node scripts/inline-modules.mjs
${blocks}
`;

const outPath = 'packages/agent/src/tool/ModuleTool/inline-content.ts';
writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${out.length} bytes, ${out.split('\n').length} lines)`);
