export function getMemoryWriteProposalPromptSection(): string {
  return [
    '## Memory Write Policy',
    '',
    'Do not silently write long-term research memory in the main answer.',
    'When durable project knowledge emerges, propose candidate memories via `research_memory:propose`.',
    '',
    '### Hypothesis Auto-Update Rule (CRITICAL)',
    '',
    'After EVERY tool invocation that returns substantive content (WebSearch, Browser,',
    'Literature evidence search, file analysis, Bash command results), you MUST follow',
    'this procedure before continuing to the next action:',
    '',
    '1. **Check active hypotheses**: Use `research_memory:retrieve` with intent',
    '   `hypothesis_check` and the current project_id to load active hypotheses.',
    '',
    '2. **Evaluate each hypothesis against the tool result**:',
    '   - If the result **supports** a hypothesis → call `research_memory:update_hypothesis`',
    '     to add the evidence memory ID to `supportingEvidenceIds` and optionally set',
    '     `status` to `supported` if it was `proposed`.',
    '   - If the result **contradicts** a hypothesis → call `research_memory:update_hypothesis`',
    '     to add the evidence memory ID to `contradictingEvidenceIds` and set',
    '     `status` to `weakened` (or `rejected` if the contradiction is definitive).',
    '   - If the result suggests a **new hypothesis** → propose it as a candidate via',
    '     `research_memory:propose` with type `hypothesis` and a clear statement.',
    '',
    '3. **Propose memory candidates for the tool result itself**:',
    '   After evaluating hypotheses, propose a candidate memory for the substantive',
    '   findings from the tool result. This ensures the evidence itself is preserved',
    '   as durable memory, not just the hypothesis update.',
    '',
    '### Candidate Proposal Rules',
    '',
    'Each candidate should include:',
    '- `proposedType`: One of `claim`, `decision`, `experiment`, `feedback`, `hypothesis`, `todo`',
    '- `content`: Concrete, specific finding (not vague summaries). Prefer "X achieved 0.83 F1 on Y"',
    '  over "some improvement was observed".',
    '- `rationale`: Why this deserves durable memory — links to research goals, hypotheses, or gaps.',
    '- `sourceRefs`: Reference the tool name, URL, session ID, or evidence span.',
    '- `confidence`: 0.0-1.0. Use 0.85+ for well-sourced factual claims, 0.5-0.7 for interpretive findings.',
    '',
    '### Auto-Accept Rules',
    '',
    'Candidates with `confidence >= 0.85` AND `proposedType` of `claim` or `decision`',
    'will be auto-accepted as durable memory. You may call `research_memory:accept_candidate`',
    'to accept these immediately.',
    '',
    'Candidates with `confidence < 0.6` AND `proposedType` of `hypothesis` will be',
    'auto-rejected. These require stronger evidence before they can be accepted.',
    '',
    'All other candidates enter the manual review queue and must be explicitly accepted.',
    '',
    '### Relation Rules',
    '',
    'When proposing a candidate that relates to an existing memory (e.g., an experiment',
    'that supports a hypothesis, or a decision that supersedes a prior decision), use',
    '`research_memory:manage_relations` to create explicit relations between them.',
    'This builds the knowledge graph that enables cross-memory reasoning.',
    '',
    '### Retrieval Configuration',
    '',
    'The `research_memory:retrieve` tool supports semantic (vector) search by default.',
    'If you encounter issues with embedding-based retrieval or prefer keyword-only search,',
    'set `enableSemanticSearch: false` in the tool call. The system will fall back to',
    'SQL LIKE pattern matching on content and summary fields.',
    '',
    '### Frequency',
    '',
    'Propose candidates and update hypotheses at natural checkpoints — after each major',
    'search batch, after analyzing a paper, after completing an experiment analysis.',
    'Do NOT propose candidates for trivial or intermediate findings.',
  ].join('\n')
}