#!/usr/bin/env node
/**
 * Generate per-provider model data for @duya/ai from models.dev.
 *
 * models.dev (https://models.dev/api.json) is a community-maintained catalog
 * of model metadata. This script maps its providers into duya's Model type
 * (maxTokens = limit.output, contextWindow = limit.context, image support from
 * modalities.input, reasoning, and $/million cost) and emits typed provider
 * shards plus an aggregator under src/providers/generated/.
 *
 * Run:  npm run generate:models -w @duya/ai
 * Flags:  --providers=openai,anthropic  restrict to a comma-separated subset
 *         --strict                     exit non-zero on any fetch/mapping error
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(__dirname, '..');
const OUT_DIR = join(packageRoot, 'src/providers/data');

const MODELS_DEV_URL = 'https://models.dev/api.json';

const args = process.argv.slice(2);
const strict = args.includes('--strict');
const providerFilterFlag = args.find((a) => a.startsWith('--providers='));
const providerFilter = new Set(
  (providerFilterFlag ? providerFilterFlag.split('=')[1] : '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
);

/**
 * Map a models.dev provider slug to duya provider metadata.
 * `api` is duya's ApiFormat. Providers absent here (local or not in models.dev)
 * are skipped by the generator.
 */
const PROVIDER_CONFIG = {
  anthropic: { providerId: 'anthropic', api: 'anthropic', baseUrl: 'https://api.anthropic.com' },
  openai: { providerId: 'openai', api: 'openai-responses', baseUrl: 'https://api.openai.com/v1' },
  deepseek: { providerId: 'deepseek', api: 'openai-chat', baseUrl: 'https://api.deepseek.com/v1' },
  google: { providerId: 'gemini', api: 'gemini', baseUrl: 'https://generativelanguage.googleapis.com/v1beta' },
  alibaba: { providerId: 'qwen', api: 'openai-chat', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1' },
  zai: { providerId: 'glm', api: 'openai-chat', baseUrl: 'https://api.z.ai/api/paas/v4' },
  moonshotai: { providerId: 'kimi', api: 'openai-chat', baseUrl: 'https://api.moonshot.ai/v1' },
  minimax: { providerId: 'minimax', api: 'anthropic', baseUrl: 'https://api.minimax.io/anthropic' },
  openrouter: { providerId: 'openrouter', api: 'openai-chat', baseUrl: 'https://openrouter.ai/api/v1' },
  xai: { providerId: 'xai', api: 'openai-chat', baseUrl: 'https://api.x.ai/v1' },
  stepfun: { providerId: 'stepfun', api: 'openai-chat', baseUrl: 'https://api.stepfun.com/v1' },
};

/** models.dev entries that are not tool-capable should be excluded. */
function isToolCapable(m) {
  return m.tool_call === true;
}

function roundCost(value) {
  return Number(value.toFixed(6));
}

function buildCost(c) {
  if (!c) return undefined;
  const tiers = (c.tiers ?? [])
    .flatMap((tier) => {
      const ctx = tier.tier;
      if (ctx?.type !== 'context' || ctx.size === undefined) return [];
      return [
        {
          inputTokensAbove: ctx.size,
          input: roundCost(tier.input ?? 0),
          output: roundCost(tier.output ?? 0),
          cacheRead: roundCost(tier.cache_read ?? 0),
          cacheWrite: roundCost(tier.cache_write ?? 0),
        },
      ];
    })
    .sort((a, b) => a.inputTokensAbove - b.inputTokensAbove);
  return {
    input: roundCost(c.input ?? 0),
    output: roundCost(c.output ?? 0),
    cacheRead: roundCost(c.cache_read ?? 0),
    cacheWrite: roundCost(c.cache_write ?? 0),
    ...(tiers.length > 0 ? { tiers } : {}),
  };
}

function toModel(provider, modelId, m) {
  const input = m.modalities?.input?.includes('image') ? ['text', 'image'] : ['text'];
  const cost = buildCost(m.cost);
  return {
    id: modelId,
    name: m.name || modelId,
    api: provider.api,
    providerId: provider.providerId,
    baseUrl: provider.baseUrl,
    reasoning: m.reasoning === true,
    input,
    contextWindow: m.limit?.context ?? 4096,
    maxTokens: m.limit?.output ?? 4096,
    ...(cost ? { cost } : {}),
  };
}

async function fetchModelsDev() {
  const res = await fetch(MODELS_DEV_URL);
  if (!res.ok) throw new Error(`models.dev returned HTTP ${res.status}`);
  return res.json();
}

function emitProviderShard(provider, models) {
  const header = `// Auto-generated by scripts/generate-models.mjs. Do not edit manually.\n`;
  const lines = models.map((m) => `  ${JSON.stringify(m)},`);
  return (
    `${header}import type { Model } from '../../types.js';\n\n` +
    `export const ${provider.providerId}Models: Model<'${provider.api}'>[] = [\n` +
    `${lines.join('\n')}\n` +
    `];\n`
  );
}

function emitAggregator(providers) {
  const header = `// Auto-generated by scripts/generate-models.mjs. Do not edit manually.\n`;
  const imports = providers
    .map((p) => `import { ${p.providerId}Models } from './${p.providerId}.models.js';`)
    .join('\n');
  const spreads = providers.map((p) => `  ...${p.providerId}Models,`).join('\n');
  return (
    `${header}${imports}\n\n` +
    `import type { Model } from '../../types.js';\n\n` +
    `export const generatedProviderModels: Model[] = [\n` +
    `${spreads}\n` +
    `];\n`
  );
}

async function main() {
  const data = await fetchModelsDev();
  const emitted = [];

  const slugs = Object.keys(PROVIDER_CONFIG)
    .filter((slug) => providerFilter.size === 0 || providerFilter.has(slug))
    .sort();

  const errors = [];
  for (const slug of slugs) {
    const provider = PROVIDER_CONFIG[slug];
    const group = data[slug];
    if (!group?.models) {
      errors.push(`models.dev has no "${slug}" group`);
      continue;
    }
    const models = Object.entries(group.models)
      .filter(([, m]) => isToolCapable(m))
      .map(([modelId, m]) => toModel(provider, modelId, m))
      .sort((a, b) => a.id.localeCompare(b.id));
    if (models.length === 0) {
      errors.push(`provider "${slug}" yielded no tool-capable models`);
      continue;
    }
    writeFileSync(join(OUT_DIR, `${provider.providerId}.models.ts`), emitProviderShard(provider, models));
    emitted.push(provider);
    console.log(`  ${provider.providerId}: ${models.length} models`);
  }

  if (emitted.length === 0) {
    throw new Error('No providers generated — check --providers filter and network access');
  }

  writeFileSync(join(OUT_DIR, 'index.ts'), emitAggregator(emitted));
  console.log(`Generated ${emitted.length} provider shards under ${OUT_DIR}`);
  if (errors.length > 0) {
    console.warn(`Warnings (${errors.length}):\n  ${errors.join('\n  ')}`);
    if (strict) process.exitCode = 1;
  }
}

mkdirSync(OUT_DIR, { recursive: true });
main().catch((err) => {
  console.error(`generate-models failed: ${err.message}`);
  process.exitCode = 1;
});