// Model data. Sourced from https://openrouter.ai/api/v1/models (public,
// no key). OpenRouter is a no-auth cross-provider model directory whose
// `context_length` / `top_provider.max_completion_tokens` /
// `supported_parameters` / `architecture.input_modalities` mirror what the
// direct api.anthropic.com endpoint advertises, so the static
// list here matches what users actually get when they hit the baseUrl below.
import type { Model } from '../types.js';

export const anthropicModels: Model<'anthropic'>[] = [
  {
    id: 'claude-opus-5',
    name: "Claude Opus 5",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'claude-sonnet-5',
    name: "Anthropic: Claude Sonnet 5",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000002,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0.000003,
    },
  },
  {
    id: 'claude-opus-4.8',
    name: "Anthropic: Claude Opus 4.8",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'claude-opus-4.7',
    name: "Anthropic: Claude Opus 4.7",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'claude-opus-4.6',
    name: "Anthropic: Claude Opus 4.6",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'claude-opus-4.5',
    name: "Anthropic: Claude Opus 4.5",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 64000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'claude-sonnet-4.6',
    name: "Anthropic: Claude Sonnet 4.6",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'claude-sonnet-4.5',
    name: "Anthropic: Claude Sonnet 4.5",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 64000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'claude-haiku-4.5',
    name: "Anthropic: Claude Haiku 4.5",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 64000,
    cost: {
      input: 0.000001,
      output: 0.000005,
      cacheRead: 0,
      cacheWrite: 0.000001,
    },
  },
  {
    id: 'claude-opus-4.1',
    name: "Anthropic: Claude Opus 4.1",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 32000,
    cost: {
      input: 0.000015,
      output: 0.000075,
      cacheRead: 0.000002,
      cacheWrite: 0.000019,
    },
  },
  {
    id: 'claude-opus-4',
    name: "Anthropic: Claude Opus 4",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 32000,
    cost: {
      input: 0.000015,
      output: 0.000075,
      cacheRead: 0.000002,
      cacheWrite: 0.000019,
    },
  },
  {
    id: 'claude-sonnet-4',
    name: "Anthropic: Claude Sonnet 4",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 64000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'claude-3-haiku',
    name: "Anthropic: Claude 3 Haiku",
    api: 'anthropic',
    providerId: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 4096,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
];
