import type { ProviderCatalogEntry } from './catalog.js';

/**
 * Built-in provider catalog data.
 *
 * Migrated from the frontend `src/lib/provider-presets.tsx` `VENDOR_PRESETS`
 * so @duya/ai is the single source of truth for provider metadata.
 *
 * Field mapping (frontend VendorPreset -> ProviderCatalogEntry):
 *   key -> id, protocol 'openai-compatible' -> 'openai-chat',
 *   authStyle -> authTypes, defaultEnvOverrides -> envOverrides,
 *   fields -> fields, category -> category, defaultModels[*].upstreamModelId kept.
 *
 * Domain field mapping (frontend ProviderPreset -> ProviderCatalogEntry):
 *   preset.category -> providerCategory,
 *   preset.authFields -> authFields,
 *   preset.modelsSource -> modelsSource,
 *   preset.defaultModelLabels -> defaultModelLabels,
 *   preset.endpointCandidates -> endpointCandidates,
 *   preset.ui.iconColor -> iconColor,
 *   preset.ui.websiteUrl -> websiteUrl,
 *   preset.legacyProtocol -> legacyProtocol.
 */

/** Shared API-key auth field for providers that use a single API key. */
const API_KEY_AUTH_FIELDS = [
  { key: 'api_key', label: 'API Key', secret: true, required: true },
];

/** Bearer-token auth field used by managed providers (Bedrock / Vertex). */
const BEARER_TOKEN_AUTH_FIELDS = [
  { key: 'api_key', label: 'Bearer Token', secret: true, required: true },
];

/** Base-URL auth field used by local providers (Ollama). */
const BASE_URL_AUTH_FIELDS = [
  { key: 'base_url', label: 'Base URL', secret: false, required: true },
];

export const BUILTIN_CATALOG_ENTRIES: ProviderCatalogEntry[] = [
  // ── Official Anthropic ──
  {
    id: 'anthropic-official',
    name: 'Anthropic',
    descriptionZh: 'Anthropic 官方 Claude API',
    protocol: 'anthropic',
    authTypes: ['api_key'],
    baseUrl: 'https://api.anthropic.com',
    envOverrides: {},
    defaultModels: [
      { modelId: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { modelId: 'claude-opus-4-7', displayName: 'Claude Opus 4.7' },
      { modelId: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { modelId: 'claude-haiku-4-5', displayName: 'Claude Haiku 4.5' },
    ],
    fields: ['api_key'],
    iconKey: 'anthropic',
    meta: {
      apiKeyUrl: 'https://console.anthropic.com/',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#D4915D',
    websiteUrl: 'https://www.anthropic.com',
    legacyProtocol: 'anthropic',
  },

  // ── Anthropic Third-party (generic) ──
  {
    id: 'anthropic-thirdparty',
    name: 'Anthropic Third-party API',
    descriptionZh: 'Anthropic 兼容第三方 API — 填写地址和密钥',
    protocol: 'anthropic',
    authTypes: ['api_key'],
    baseUrl: '',
    envOverrides: { ANTHROPIC_API_KEY: '' },
    defaultModels: [
      { modelId: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { modelId: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { modelId: 'claude-haiku-4-5', displayName: 'Claude Haiku 4.5' },
    ],
    fields: ['name', 'api_key', 'base_url', 'extra_env', 'model_mapping'],
    iconKey: 'server',
    providerCategory: 'custom',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    legacyProtocol: 'anthropic',
  },

  // ── OpenRouter ──
  {
    id: 'openrouter',
    name: 'OpenRouter',
    descriptionZh: '通过 OpenRouter 访问 100+ 模型',
    protocol: 'openrouter',
    authTypes: ['auth_token'],
    baseUrl: 'https://openrouter.ai/api/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'anthropic/claude-3.5-sonnet', displayName: 'Claude 3.5 Sonnet' },
      { modelId: 'anthropic/claude-3-opus', displayName: 'Claude 3 Opus' },
      { modelId: 'anthropic/claude-3-haiku', displayName: 'Claude 3 Haiku' },
    ],
    fields: ['api_key'],
    iconKey: 'openrouter',
    meta: {
      apiKeyUrl: 'https://openrouter.ai/keys',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/models' },
    websiteUrl: 'https://openrouter.ai',
    legacyProtocol: 'openrouter',
  },

  // ── DeepSeek ──
  {
    id: 'deepseek',
    name: 'DeepSeek',
    descriptionZh: 'DeepSeek Anthropic 兼容 API — V4 Pro / V4 Flash',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.deepseek.com/anthropic',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    defaultModels: [
      { modelId: 'deepseek-v4-pro', displayName: 'DeepSeek V4 Pro' },
      { modelId: 'deepseek-v4-flash', displayName: 'DeepSeek V4 Flash' },
      { modelId: 'deepseek-chat', displayName: 'DeepSeek Chat' },
      { modelId: 'deepseek-reasoner', displayName: 'DeepSeek Reasoner' },
    ],
    fields: ['api_key'],
    iconKey: 'deepseek',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.deepseek.com/api_keys',
      docsUrl: 'https://platform.deepseek.com/docs',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#1E88E5',
    websiteUrl: 'https://platform.deepseek.com',
    legacyProtocol: 'anthropic',
  },

  // ── Zhipu GLM (China) ──
  {
    id: 'glm-cn',
    name: 'GLM (CN)',
    descriptionZh: '智谱 GLM 编程套餐 — 中国区',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://open.bigmodel.cn/api/anthropic',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
    },
    defaultModels: [
      { modelId: 'glm-5.1', displayName: 'GLM-5.1' },
      { modelId: 'glm-5', displayName: 'GLM-5' },
      { modelId: 'glm-5-turbo', displayName: 'GLM-5 Turbo' },
      { modelId: 'glm-5v-turbo', displayName: 'GLM-5V Turbo' },
      { modelId: 'glm-4.7', displayName: 'GLM-4.7' },
      { modelId: 'glm-4.5', displayName: 'GLM-4.5' },
      { modelId: 'glm-4.5-flash', displayName: 'GLM-4.5 Flash' },
      { modelId: 'glm-4.5-air', displayName: 'GLM-4.5 Air' },
    ],
    fields: ['api_key'],
    iconKey: 'zhipu',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://bigmodel.cn/usercenter/proj-mgmt/apikeys',
      docsUrl: 'https://docs.bigmodel.cn/cn/coding-plan/tool/claude',
      billingModel: 'coding_plan',
      notes: ['高峰时段（14:00-18:00 UTC+8）消耗 3 倍积分'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#0F62FE',
    websiteUrl: 'https://bigmodel.cn',
    legacyProtocol: 'anthropic',
  },

  // ── Zhipu GLM (Global) ──
  {
    id: 'glm-global',
    name: 'GLM (Global)',
    descriptionZh: '智谱 GLM 编程套餐 — 国际区',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.z.ai/api/anthropic',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
    },
    defaultModels: [
      { modelId: 'glm-5.1', displayName: 'GLM-5.1' },
      { modelId: 'glm-5', displayName: 'GLM-5' },
      { modelId: 'glm-5-turbo', displayName: 'GLM-5 Turbo' },
      { modelId: 'glm-5v-turbo', displayName: 'GLM-5V Turbo' },
      { modelId: 'glm-4.7', displayName: 'GLM-4.7' },
      { modelId: 'glm-4.5', displayName: 'GLM-4.5' },
      { modelId: 'glm-4.5-flash', displayName: 'GLM-4.5 Flash' },
      { modelId: 'glm-4.5-air', displayName: 'GLM-4.5 Air' },
    ],
    fields: ['api_key'],
    iconKey: 'zhipu',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://z.ai/manage-apikey/apikey-list',
      docsUrl: 'https://docs.z.ai/devpack/tool/claude',
      billingModel: 'coding_plan',
      notes: ['高峰时段（14:00-18:00 UTC+8）消耗 3 倍积分'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#0F62FE',
    websiteUrl: 'https://z.ai',
    legacyProtocol: 'anthropic',
  },

  // ── Kimi ──
  {
    id: 'kimi',
    name: 'Kimi',
    descriptionZh: 'Kimi 编程计划 API',
    protocol: 'anthropic',
    authTypes: ['api_key'],
    baseUrl: 'https://api.kimi.com/coding/',
    envOverrides: { ENABLE_TOOL_SEARCH: 'false' },
    defaultModels: [
      { modelId: 'kimi-k2.6', displayName: 'Kimi K2.6' },
      { modelId: 'kimi-k2.5', displayName: 'Kimi K2.5' },
      { modelId: 'kimi-k2', displayName: 'Kimi K2' },
      { modelId: 'kimi-k2-thinking', displayName: 'Kimi K2 Thinking' },
      { modelId: 'kimi-k2-thinking-turbo', displayName: 'Kimi K2 Thinking Turbo' },
      { modelId: 'kimi-k2-turbo-preview', displayName: 'Kimi K2 Turbo Preview' },
      { modelId: 'kimi-k2-0905-preview', displayName: 'Kimi K2 Preview (0905)' },
    ],
    fields: ['api_key'],
    iconKey: 'kimi',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://www.kimi.com/code/console',
      docsUrl: 'https://www.kimi.com/code/docs/more/third-party-agents.html',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#6366F1',
    websiteUrl: 'https://www.kimi.com',
    legacyProtocol: 'anthropic',
  },

  // ── Moonshot ──
  {
    id: 'moonshot',
    name: 'Moonshot',
    descriptionZh: '月之暗面 API',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.moonshot.cn/anthropic',
    envOverrides: { ENABLE_TOOL_SEARCH: 'false' },
    defaultModels: [
      { modelId: 'kimi-k2.6', displayName: 'Kimi K2.6' },
      { modelId: 'kimi-k2.5', displayName: 'Kimi K2.5' },
      { modelId: 'kimi-k2', displayName: 'Kimi K2' },
      { modelId: 'kimi-k2-thinking', displayName: 'Kimi K2 Thinking' },
      { modelId: 'kimi-k2-thinking-turbo', displayName: 'Kimi K2 Thinking Turbo' },
      { modelId: 'kimi-k2-turbo-preview', displayName: 'Kimi K2 Turbo Preview' },
      { modelId: 'kimi-k2-0905-preview', displayName: 'Kimi K2 Preview (0905)' },
    ],
    fields: ['api_key'],
    iconKey: 'moonshot',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
      docsUrl: 'https://platform.moonshot.cn/docs/guide/agent-support',
      billingModel: 'pay_as_you_go',
      notes: ['建议设置每日消费上限，防止 agentic 循环快速消耗 token'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#6366F1',
    websiteUrl: 'https://platform.moonshot.cn',
    legacyProtocol: 'anthropic',
  },

  // ── StepFun Step Plan ──
  {
    id: 'stepfun',
    name: 'StepFun Step Plan',
    descriptionZh: '阶跃星辰 Step Plan — 快速推理与编程',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.stepfun.ai/step_plan/v1',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
    },
    defaultModels: [
      { modelId: 'step-3.5-flash', displayName: 'Step-3.5 Flash' },
      { modelId: 'step-3.5-flash-2603', displayName: 'Step-3.5 Flash (2603)' },
    ],
    fields: ['api_key'],
    iconKey: 'stepfun',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.stepfun.com/api',
      docsUrl: 'https://platform.stepfun.com/docs',
      billingModel: 'coding_plan',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://platform.stepfun.com',
    legacyProtocol: 'anthropic',
  },

  // ── MiniMax (China) ──
  {
    id: 'minimax-cn',
    name: 'MiniMax (CN)',
    descriptionZh: 'MiniMax 编程套餐 — 中国区',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.minimaxi.com/anthropic',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    defaultModels: [
      { modelId: 'MiniMax-M3', displayName: 'MiniMax-M3' },
      { modelId: 'MiniMax-M2.7', displayName: 'MiniMax-M2.7' },
      { modelId: 'MiniMax-M2.5', displayName: 'MiniMax-M2.5' },
      { modelId: 'MiniMax-M2.1', displayName: 'MiniMax-M2.1' },
      { modelId: 'MiniMax-M2', displayName: 'MiniMax-M2' },
    ],
    fields: ['api_key'],
    iconKey: 'minimax',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.minimaxi.com/user-center/payment/token-plan',
      docsUrl: 'https://platform.minimaxi.com/docs/token-plan/claude-code',
      billingModel: 'token_plan',
      notes: ['中国区用户专用，需要 MiniMax 编程套餐订阅'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#FF6B6B',
    websiteUrl: 'https://platform.minimaxi.com',
    legacyProtocol: 'anthropic',
  },

  // ── MiniMax (Global) ──
  {
    id: 'minimax',
    name: 'MiniMax (Global)',
    descriptionZh: 'MiniMax 编程套餐 — 国际区',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.minimax.io/anthropic',
    envOverrides: {
      API_TIMEOUT_MS: '3000000',
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
    },
    defaultModels: [
      { modelId: 'MiniMax-M3', displayName: 'MiniMax-M3' },
      { modelId: 'MiniMax-M2.7', displayName: 'MiniMax-M2.7' },
      { modelId: 'MiniMax-M2.5', displayName: 'MiniMax-M2.5' },
      { modelId: 'MiniMax-M2.1', displayName: 'MiniMax-M2.1' },
      { modelId: 'MiniMax-M2', displayName: 'MiniMax-M2' },
    ],
    fields: ['api_key'],
    iconKey: 'minimax',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.minimax.io/user-center/payment/token-plan',
      docsUrl: 'https://platform.minimax.io/docs/token-plan/opencode',
      billingModel: 'token_plan',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#FF6B6B',
    websiteUrl: 'https://platform.minimax.io',
    legacyProtocol: 'anthropic',
  },

  // ── Volcengine Ark ──
  {
    id: 'volcengine',
    name: 'Volcengine Ark',
    descriptionZh: '字节火山方舟 Coding Plan — 豆包、GLM、DeepSeek、Kimi',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    envOverrides: {},
    defaultModels: [
      { modelId: 'doubao-1.5-pro-32k', displayName: 'Doubao 1.5 Pro 32K' },
      { modelId: 'doubao-1.5-lite-32k', displayName: 'Doubao 1.5 Lite 32K' },
      { modelId: 'doubao-pro-32k', displayName: 'Doubao Pro 32K' },
      { modelId: 'doubao-lite-32k', displayName: 'Doubao Lite 32K' },
      { modelId: 'deepseek-v3-241226', displayName: 'DeepSeek V3 (241226)' },
      { modelId: 'deepseek-r1-250120', displayName: 'DeepSeek R1 (250120)' },
      { modelId: 'glm-4-9b-chat', displayName: 'GLM-4 9B Chat' },
      { modelId: 'glm-4-flash', displayName: 'GLM-4 Flash' },
      { modelId: 'kimi-k2.5', displayName: 'Kimi K2.5' },
    ],
    fields: ['api_key', 'model_names'],
    iconKey: 'volcengine',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement',
      docsUrl: 'https://www.volcengine.com/docs/82379/1928262',
      billingModel: 'coding_plan',
      notes: ['需先在控制台激活 Endpoint', 'API Key 为临时凭证'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#FF6A00',
    websiteUrl: 'https://www.volcengine.com',
    legacyProtocol: 'anthropic',
  },

  // ── Xiaomi MiMo (按量付费) ──
  {
    id: 'xiaomi-mimo',
    name: 'Xiaomi MiMo',
    descriptionZh: '小米 MiMo 按量付费 — MiMo-V2.5-Pro',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.xiaomimimo.com/anthropic',
    envOverrides: {},
    defaultModels: [
      { modelId: 'mimo-v2.5-pro', displayName: 'MiMo-V2.5-Pro' },
      { modelId: 'mimo-v2.5', displayName: 'MiMo-V2.5' },
      { modelId: 'mimo-v2-pro', displayName: 'MiMo-V2-Pro' },
      { modelId: 'mimo-v2-omni', displayName: 'MiMo-V2-Omni' },
      { modelId: 'mimo-v2-flash', displayName: 'MiMo-V2-Flash' },
    ],
    fields: ['api_key'],
    iconKey: 'xiaomi',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/api-keys',
      docsUrl: 'https://platform.xiaomimimo.com/#/docs/integration/claudecode',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://api.xiaomimimo.com',
    legacyProtocol: 'anthropic',
  },

  // ── Xiaomi MiMo Token Plan ──
  {
    id: 'xiaomi-mimo-token-plan',
    name: 'Xiaomi MiMo Token Plan',
    descriptionZh: '小米 MiMo Token Plan 订阅套餐',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
    envOverrides: {},
    defaultModels: [
      { modelId: 'mimo-v2.5-pro', displayName: 'MiMo-V2.5-Pro' },
      { modelId: 'mimo-v2.5', displayName: 'MiMo-V2.5' },
      { modelId: 'mimo-v2-pro', displayName: 'MiMo-V2-Pro' },
      { modelId: 'mimo-v2-omni', displayName: 'MiMo-V2-Omni' },
    ],
    fields: ['api_key'],
    iconKey: 'xiaomi',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/plan-manage',
      docsUrl: 'https://platform.xiaomimimo.com/#/docs/integration/claudecode',
      billingModel: 'token_plan',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://api.xiaomimimo.com',
    legacyProtocol: 'anthropic',
  },

  // ── xAI Grok ──
  {
    id: 'xai',
    name: 'xAI Grok',
    descriptionZh: 'xAI Grok — 快速推理模型',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.x.ai/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'grok-4.20-reasoning', displayName: 'Grok 4.20 Reasoning' },
      { modelId: 'grok-4-1-fast-reasoning', displayName: 'Grok 4-1 Fast Reasoning' },
    ],
    fields: ['api_key'],
    iconKey: 'xai',
    meta: {
      apiKeyUrl: 'https://console.x.ai/',
      docsUrl: 'https://docs.x.ai/docs',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://console.x.ai/',
    legacyProtocol: 'anthropic',
  },

  // ── Arcee ──
  {
    id: 'arcee',
    name: 'Arcee',
    descriptionZh: 'Arcee AI — Trinity 大型推理模型',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://api.arcee.ai/api/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'trinity-large-thinking', displayName: 'Trinity Large Thinking' },
      { modelId: 'trinity-large-preview', displayName: 'Trinity Large Preview' },
      { modelId: 'trinity-mini', displayName: 'Trinity Mini' },
    ],
    fields: ['api_key'],
    iconKey: 'arcee',
    meta: {
      apiKeyUrl: 'https://www.arcee.ai/',
      docsUrl: 'https://docs.arcee.ai/',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://www.arcee.ai/',
    legacyProtocol: 'anthropic',
  },

  // ── Aliyun Bailian ──
  {
    id: 'bailian',
    name: 'Aliyun Bailian',
    descriptionZh: '阿里云百炼 Coding Plan — 通义千问、GLM、Kimi、MiniMax',
    protocol: 'anthropic',
    authTypes: ['auth_token'],
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    envOverrides: {},
    defaultModels: [
      { modelId: 'qwen3.6-plus', displayName: 'Qwen 3.6 Plus' },
      { modelId: 'qwen3.5-plus', displayName: 'Qwen 3.5 Plus' },
      { modelId: 'qwen3.5-plus-02-15', displayName: 'Qwen 3.5 Plus (02-15)' },
      { modelId: 'qwen3.5-35b-a3b', displayName: 'Qwen 3.5 35B A3B' },
      { modelId: 'qwen3-coder-next', displayName: 'Qwen 3 Coder Next' },
      { modelId: 'qwen3-coder-plus', displayName: 'Qwen 3 Coder Plus' },
      { modelId: 'qwen3-coder', displayName: 'Qwen 3 Coder' },
      { modelId: 'kimi-k2.6', displayName: 'Kimi K2.6' },
      { modelId: 'kimi-k2.5', displayName: 'Kimi K2.5' },
      { modelId: 'kimi-k2-thinking', displayName: 'Kimi K2 Thinking' },
      { modelId: 'glm-5.1', displayName: 'GLM-5.1' },
      { modelId: 'glm-5', displayName: 'GLM-5' },
      { modelId: 'glm-4.7', displayName: 'GLM-4.7' },
      { modelId: 'MiniMax-M2.7', displayName: 'MiniMax-M2.7' },
      { modelId: 'MiniMax-M2.5', displayName: 'MiniMax-M2.5' },
    ],
    fields: ['api_key'],
    iconKey: 'bailian',
    sdkProxyOnly: true,
    meta: {
      apiKeyUrl: 'https://bailian.console.aliyun.com',
      docsUrl: 'https://help.aliyun.com/zh/model-studio/coding-plan',
      billingModel: 'coding_plan',
      notes: ['必须使用 Coding Plan 专用 Key（以 sk-sp- 开头）', '普通 DashScope Key 无法使用', '禁止用于自动化脚本'],
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#FF6A00',
    websiteUrl: 'https://bailian.console.aliyun.com',
    legacyProtocol: 'anthropic',
  },

  // ── AWS Bedrock ──
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    descriptionZh: 'Amazon Bedrock — 需要 AWS 凭证',
    protocol: 'bedrock',
    authTypes: ['env_only'],
    baseUrl: '',
    envOverrides: {
      CLAUDE_CODE_USE_BEDROCK: '1',
      AWS_REGION: 'us-east-1',
      CLAUDE_CODE_SKIP_BEDROCK_AUTH: '1',
    },
    defaultModels: [
      { modelId: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { modelId: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { modelId: 'claude-haiku-4-5', displayName: 'Claude Haiku 4.5' },
    ],
    fields: ['extra_env'],
    iconKey: 'bedrock',
    meta: {
      apiKeyUrl: 'https://console.aws.amazon.com',
      docsUrl: 'https://aws.amazon.com/cn/bedrock/anthropic/',
      billingModel: 'pay_as_you_go',
      notes: ['需在 AWS Console 订阅 Claude 模型'],
    },
    providerCategory: 'managed',
    authFields: BEARER_TOKEN_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://aws.amazon.com/bedrock',
    legacyProtocol: 'bedrock',
  },

  // ── Google Vertex AI ──
  {
    id: 'vertex',
    name: 'Google Vertex',
    descriptionZh: 'Google Vertex AI — 需要 GCP 凭证',
    protocol: 'vertex',
    authTypes: ['env_only'],
    baseUrl: '',
    envOverrides: {
      CLAUDE_CODE_USE_VERTEX: '1',
      CLOUD_ML_REGION: 'us-east5',
      CLAUDE_CODE_SKIP_VERTEX_AUTH: '1',
    },
    defaultModels: [
      { modelId: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { modelId: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { modelId: 'claude-haiku-4-5', displayName: 'Claude Haiku 4.5' },
    ],
    fields: ['extra_env'],
    iconKey: 'google',
    meta: {
      docsUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude',
      billingModel: 'pay_as_you_go',
      notes: ['需启用 Vertex AI 并在 Model Garden 订阅 Claude 模型'],
    },
    providerCategory: 'managed',
    authFields: BEARER_TOKEN_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    iconColor: '#4285F4',
    websiteUrl: 'https://cloud.google.com/vertex-ai',
    legacyProtocol: 'vertex',
  },

  // ── Ollama ──
  {
    id: 'ollama',
    name: 'Ollama',
    descriptionZh: 'Ollama — 本地运行模型，原生 API',
    protocol: 'ollama',
    authTypes: ['auth_token'],
    baseUrl: 'http://localhost:11434',
    envOverrides: {
      OPENAI_API_KEY: 'ollama',
    },
    defaultModels: [
      { modelId: 'llama3.2', displayName: 'Llama 3.2' },
      { modelId: 'qwen2.5', displayName: 'Qwen 2.5' },
      { modelId: 'codellama', displayName: 'CodeLlama' },
      { modelId: 'mistral', displayName: 'Mistral' },
      { modelId: 'deepseek-coder', displayName: 'DeepSeek Coder' },
    ],
    fields: ['base_url', 'model_names'],
    iconKey: 'ollama',
    meta: {
      docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/api.md',
      billingModel: 'free',
      notes: [
        '需要本地安装 Ollama (https://ollama.com)',
        '使用 Ollama 原生 API 端点 (非 OpenAI 兼容模式)',
        '支持工具调用和思考内容',
        'API Key 可填写任意值，本地运行无需验证',
        '不确定能运行什么模型？用 CanIRun.ai 检测: https://www.canirun.ai/',
      ],
    },
    providerCategory: 'local',
    authFields: BASE_URL_AUTH_FIELDS,
    modelsSource: { type: 'custom-url', url: '/api/tags' },
    endpointCandidates: ['http://localhost:11434', 'http://127.0.0.1:11434'],
    websiteUrl: 'https://ollama.com',
    legacyProtocol: 'ollama',
  },

  // ── LiteLLM ──
  {
    id: 'litellm',
    name: 'LiteLLM',
    descriptionZh: 'LiteLLM 代理 — 本地或远程',
    protocol: 'anthropic',
    authTypes: ['api_key'],
    baseUrl: 'http://localhost:4000',
    envOverrides: {},
    defaultModels: [
      { modelId: 'claude-sonnet-4-6', displayName: 'Claude Sonnet 4.6' },
      { modelId: 'claude-opus-4-6', displayName: 'Claude Opus 4.6' },
      { modelId: 'claude-haiku-4-5', displayName: 'Claude Haiku 4.5' },
    ],
    fields: ['api_key', 'base_url'],
    iconKey: 'server',
    meta: {
      docsUrl: 'https://docs.litellm.ai/docs/',
      billingModel: 'self_hosted',
    },
    providerCategory: 'aggregator',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/v1/models' },
    websiteUrl: 'https://github.com/BerriAI/litellm',
    legacyProtocol: 'openai-compatible',
  },

  // ════════════════════════════════════════════════════════════════
  // ── Missing providers (exist in frontend presets, were absent here) ──
  // ════════════════════════════════════════════════════════════════

  // ── OpenAI Official ──
  {
    id: 'openai-official',
    name: 'OpenAI',
    descriptionZh: 'OpenAI 官方 API — GPT-4o / o1 / o3 系列',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: 'https://api.openai.com/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'gpt-4o', displayName: 'GPT-4o' },
      { modelId: 'gpt-4o-mini', displayName: 'GPT-4o Mini' },
      { modelId: 'o1', displayName: 'o1' },
      { modelId: 'o1-mini', displayName: 'o1 Mini' },
      { modelId: 'o3-mini', displayName: 'o3 Mini' },
    ],
    fields: ['api_key'],
    iconKey: 'openai',
    meta: {
      apiKeyUrl: 'https://platform.openai.com/api-keys',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/models' },
    iconColor: '#00A67E',
    websiteUrl: 'https://platform.openai.com',
    legacyProtocol: 'openai',
  },

  // ── OpenAI-Compatible Generic ──
  {
    id: 'openai-compatible-generic',
    name: 'OpenAI-Compatible (Generic)',
    descriptionZh: 'OpenAI 兼容 API — 填写地址和密钥',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: '',
    envOverrides: {},
    defaultModels: [],
    fields: ['name', 'api_key', 'base_url'],
    iconKey: 'server',
    providerCategory: 'custom',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/models' },
    legacyProtocol: 'openai-compatible',
  },

  // ── DeepSeek (OpenAI-compatible) ──
  {
    id: 'deepseek-openai',
    name: 'DeepSeek (OpenAI)',
    descriptionZh: 'DeepSeek OpenAI 兼容 API — R1 / V3',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: 'https://api.deepseek.com/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'deepseek-reasoner', displayName: 'DeepSeek R1 (Reasoning)' },
      { modelId: 'deepseek-chat', displayName: 'DeepSeek V3 (Chat)' },
    ],
    fields: ['api_key'],
    iconKey: 'deepseek',
    meta: {
      apiKeyUrl: 'https://platform.deepseek.com/api_keys',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://platform.deepseek.com',
    legacyProtocol: 'openai-compatible',
  },

  // ── Qwen (OpenAI-compatible) ──
  {
    id: 'qwen-openai',
    name: 'Qwen (OpenAI)',
    descriptionZh: '通义千问 OpenAI 兼容 API',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'qwq-32b-preview', displayName: 'QwQ 32B Preview' },
    ],
    fields: ['api_key'],
    iconKey: 'qwen',
    meta: {
      apiKeyUrl: 'https://dashscope.console.aliyun.com/apiKey',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://dashscope.console.aliyun.com',
    legacyProtocol: 'openai-compatible',
  },

  // ── GLM (OpenAI-compatible) ──
  {
    id: 'glm-openai',
    name: 'GLM (OpenAI)',
    descriptionZh: '智谱 GLM OpenAI 兼容 API',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    envOverrides: {},
    defaultModels: [
      { modelId: 'glm-4-plus', displayName: 'GLM-4 Plus' },
    ],
    fields: ['api_key'],
    iconKey: 'zhipu',
    meta: {
      apiKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://open.bigmodel.cn',
    legacyProtocol: 'openai-compatible',
  },

  // ── Kimi (OpenAI-compatible) ──
  {
    id: 'kimi-openai',
    name: 'Kimi (OpenAI)',
    descriptionZh: 'Moonshot Kimi OpenAI 兼容 API',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: 'https://api.moonshot.cn/v1',
    envOverrides: {},
    defaultModels: [
      { modelId: 'moonshot-v1-auto', displayName: 'Moonshot V1 Auto' },
    ],
    fields: ['api_key'],
    iconKey: 'kimi',
    meta: {
      apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'static' },
    websiteUrl: 'https://platform.moonshot.cn',
    legacyProtocol: 'openai-compatible',
  },

  // ── Google Gemini ──
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    descriptionZh: 'Google Gemini — 原生 API',
    protocol: 'gemini',
    authTypes: ['api_key'],
    baseUrl: 'https://generativelanguage.googleapis.com',
    envOverrides: {},
    defaultModels: [
      { modelId: 'gemini-2.5-pro', displayName: 'Gemini 2.5 Pro' },
      { modelId: 'gemini-2.5-flash', displayName: 'Gemini 2.5 Flash' },
      { modelId: 'gemini-2.0-pro', displayName: 'Gemini 2.0 Pro' },
    ],
    fields: ['api_key'],
    iconKey: 'google',
    meta: {
      apiKeyUrl: 'https://aistudio.google.com/apikey',
      billingModel: 'pay_as_you_go',
    },
    providerCategory: 'official',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/v1beta/models' },
    iconColor: '#4285F4',
    websiteUrl: 'https://aistudio.google.com',
    legacyProtocol: 'google',
  },

  // ── Custom Anthropic ──
  {
    id: 'custom-anthropic',
    name: 'Custom Anthropic',
    descriptionZh: 'Anthropic 兼容自定义 API — 填写地址和密钥',
    protocol: 'anthropic',
    authTypes: ['api_key'],
    baseUrl: '',
    envOverrides: {},
    defaultModels: [],
    fields: ['name', 'api_key', 'base_url'],
    iconKey: 'server',
    providerCategory: 'custom',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/v1/models' },
    legacyProtocol: 'anthropic',
  },

  // ── Custom OpenAI ──
  {
    id: 'custom-openai',
    name: 'Custom OpenAI',
    descriptionZh: 'OpenAI 兼容自定义 API — 填写地址和密钥',
    protocol: 'openai-chat',
    authTypes: ['api_key'],
    baseUrl: '',
    envOverrides: {},
    defaultModels: [],
    fields: ['name', 'api_key', 'base_url'],
    iconKey: 'server',
    providerCategory: 'custom',
    authFields: API_KEY_AUTH_FIELDS,
    modelsSource: { type: 'openai-compatible-models', path: '/v1/models' },
    legacyProtocol: 'openai-compatible',
  },
];
