// Model data. MiniMax M3/M2.x via Anthropic-compatible API (Global region).
// Spec §9: M3 Anthropic defaults thinking OFF; forceAdaptiveThinking drives
// { type: 'adaptive' } in resolveAnthropicThinking.
import type { Model } from '../types.js';

export const minimaxModels: Model<'anthropic'>[] = [
  {
    id: 'MiniMax-M3',
    name: 'MiniMax M3',
    api: 'anthropic',
    providerId: 'minimax',
    baseUrl: 'https://api.minimax.io/anthropic',
    reasoning: true,
    thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', max: 'max' },
    compat: { forceAdaptiveThinking: true },
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0, tiers: [{ inputTokensAbove: 512000, input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 }] },
  },
  {
    id: 'MiniMax-M2.7',
    name: 'MiniMax M2.7',
    api: 'anthropic',
    providerId: 'minimax',
    baseUrl: 'https://api.minimax.io/anthropic',
    reasoning: true,
    thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', max: 'max' },
    compat: { forceAdaptiveThinking: true },
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0.375 },
  },
  {
    id: 'MiniMax-M2.5',
    name: 'MiniMax M2.5',
    api: 'anthropic',
    providerId: 'minimax',
    baseUrl: 'https://api.minimax.io/anthropic',
    reasoning: true,
    thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', max: 'max' },
    compat: { forceAdaptiveThinking: true },
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.375 },
  },
  {
    id: 'MiniMax-M2.1',
    name: 'MiniMax M2.1',
    api: 'anthropic',
    providerId: 'minimax',
    baseUrl: 'https://api.minimax.io/anthropic',
    reasoning: true,
    thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', max: 'max' },
    compat: { forceAdaptiveThinking: true },
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.375 },
  },
  {
    id: 'MiniMax-M2',
    name: 'MiniMax M2',
    api: 'anthropic',
    providerId: 'minimax',
    baseUrl: 'https://api.minimax.io/anthropic',
    reasoning: true,
    thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', max: 'max' },
    compat: { forceAdaptiveThinking: true },
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0 },
  },
];