// Model data. Hand-curated as the base; OpenRouter's /models endpoint
// (fetched at runtime by src/lib/providers/models/ModelSyncService.ts) still
// returns the full 400+ model list — this static file just gives the @duya/ai
// package self-contained metadata for the most-picked ones so the build doesn't
// have to hit the network for type/cost/contextWindow lookups.
//
// Metadata here was scraped live from https://openrouter.ai/api/v1/models
// (no key needed — that endpoint is public). Notable updates from this refresh:
//   - Claude 5 (opus / sonnet) added; Claude 3.x family removed
//   - GPT-5.x added; GPT-4 / GPT-3.5 kept for legacy callers
//   - Gemini 2.5 family added
//   - DeepSeek v3.2 / v4 added (current generation)
//   - Grok 4.x added
//   - MiniMax m3 now reflects the live 1M context (was hardcoded 200K which
//     made duya's auto-compaction fire at 156K instead of 780K)
import type { Model } from '../types.js';

export const openrouterModels: Model<'openai-chat'>[] = [
  {
    id: 'auto',
    name: 'OpenRouter Auto',
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 2000000,
    maxTokens: 4096,
  },
  {
    id: 'anthropic/claude-opus-5',
    name: "Claude Opus 5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'anthropic/claude-sonnet-5',
    name: "Anthropic: Claude Sonnet 5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000002,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0.000003,
    },
  },
  {
    id: 'anthropic/claude-opus-4.7',
    name: "Anthropic: Claude Opus 4.7",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'anthropic/claude-sonnet-4.6',
    name: "Anthropic: Claude Sonnet 4.6",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 128000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'anthropic/claude-opus-4.5',
    name: "Anthropic: Claude Opus 4.5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 64000,
    cost: {
      input: 0.000005,
      output: 0.000025,
      cacheRead: 0,
      cacheWrite: 0.000006,
    },
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    name: "Anthropic: Claude Sonnet 4.5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 64000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'anthropic/claude-haiku-4.5',
    name: "Anthropic: Claude Haiku 4.5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 64000,
    cost: {
      input: 0.000001,
      output: 0.000005,
      cacheRead: 0,
      cacheWrite: 0.000001,
    },
  },
  {
    id: 'anthropic/claude-opus-4.1',
    name: "Anthropic: Claude Opus 4.1",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 32000,
    cost: {
      input: 0.000015,
      output: 0.000075,
      cacheRead: 0.000002,
      cacheWrite: 0.000019,
    },
  },
  {
    id: 'anthropic/claude-opus-4',
    name: "Anthropic: Claude Opus 4",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 32000,
    cost: {
      input: 0.000015,
      output: 0.000075,
      cacheRead: 0.000002,
      cacheWrite: 0.000019,
    },
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: "Anthropic: Claude Sonnet 4",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 64000,
    cost: {
      input: 0.000003,
      output: 0.000015,
      cacheRead: 0,
      cacheWrite: 0.000004,
    },
  },
  {
    id: 'anthropic/claude-3-haiku',
    name: "Anthropic: Claude 3 Haiku",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 200000,
    maxTokens: 4096,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5',
    name: "OpenAI: GPT-5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000001,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5-mini',
    name: "OpenAI: GPT-5 Mini",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5-pro',
    name: "OpenAI: GPT-5 Pro",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000015,
      output: 0.00012,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5.1',
    name: "OpenAI: GPT-5.1",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000001,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5.1-codex',
    name: "OpenAI: GPT-5.1-Codex",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000001,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5.2',
    name: "OpenAI: GPT-5.2",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000002,
      output: 0.000014,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5.2-pro',
    name: "OpenAI: GPT-5.2 Pro",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000021,
      output: 0.000168,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-5.3-codex',
    name: "OpenAI: GPT-5.3-Codex",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 400000,
    maxTokens: 128000,
    cost: {
      input: 0.000002,
      output: 0.000014,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-4o',
    name: "OpenAI: GPT-4o",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: {
      input: 0.000003,
      output: 0.00001,
      cacheRead: 0.000001,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-4o-mini',
    name: "OpenAI: GPT-4o-mini",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-4-turbo',
    name: "OpenAI: GPT-4 Turbo",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 128000,
    maxTokens: 4096,
    cost: {
      input: 0.00001,
      output: 0.00003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'openai/gpt-3.5-turbo',
    name: "OpenAI: GPT-3.5 Turbo",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 16385,
    maxTokens: 4096,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'google/gemini-2.5-pro',
    name: "Google: Gemini 2.5 Pro",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1048576,
    maxTokens: 65536,
    cost: {
      input: 0.000001,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'google/gemini-2.5-flash',
    name: "Google: Gemini 2.5 Flash",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1048576,
    maxTokens: 65535,
    cost: {
      input: 0,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    name: "Google: Gemini 2.5 Flash Lite",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1048576,
    maxTokens: 65535,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'meta-llama/llama-3.1-70b-instruct',
    name: "Meta: Llama 3.1 70B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    name: "Meta: Llama 3.1 8B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 117964,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'meta-llama/llama-3.2-3b-instruct',
    name: "Meta: Llama 3.2 3B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 117964,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'mistralai/mistral-large',
    name: "Mistral Large",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 128000,
    maxTokens: 102400,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'mistralai/mistral-nemo',
    name: "Mistral: Mistral Nemo",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'mistralai/mixtral-8x22b-instruct',
    name: "Mistral: Mixtral 8x22B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 65536,
    maxTokens: 52428,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: "Qwen2.5 72B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen/qwen-2.5-coder-32b-instruct',
    name: "Qwen2.5 Coder 32B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 29491,
    cost: {
      input: 0.000001,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen/qwen-2.5-7b-instruct',
    name: "Qwen: Qwen2.5 7B Instruct",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 29491,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'deepseek/deepseek-chat',
    name: "DeepSeek: DeepSeek V3",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 163840,
    maxTokens: 16000,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'deepseek/deepseek-r1',
    name: "DeepSeek: R1",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 64000,
    maxTokens: 16000,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'deepseek/deepseek-v3.2',
    name: "DeepSeek: DeepSeek V3.2",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 163840,
    maxTokens: 147456,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'deepseek/deepseek-v4-pro',
    name: "DeepSeek: DeepSeek V4 Pro 0423",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 1048576,
    maxTokens: 384000,
    cost: {
      input: 0.000001,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'deepseek/deepseek-v4-flash',
    name: "DeepSeek: DeepSeek V4 Flash 0423",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 1048576,
    maxTokens: 384000,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'x-ai/grok-4.6',
    name: "SpaceXAI: Grok 4.6",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 500000,
    maxTokens: 450000,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'x-ai/grok-4.5',
    name: "SpaceXAI: Grok 4.5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 500000,
    maxTokens: 450000,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'x-ai/grok-4.3',
    name: "SpaceXAI: Grok 4.3",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 900000,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'cohere/command-r-plus-08-2024',
    name: "Cohere: Command R+ (08-2024)",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 128000,
    maxTokens: 4000,
    cost: {
      input: 0.000003,
      output: 0.00001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m3',
    name: "MiniMax: MiniMax M3",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1048576,
    maxTokens: 512000,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m3:free',
    name: "MiniMax: MiniMax M3 (free)",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1048576,
    maxTokens: 943718,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m2.7',
    name: "MiniMax: MiniMax M2.7",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 204800,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m2.5',
    name: "MiniMax: MiniMax M2.5",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 204800,
    maxTokens: 128000,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m2.1',
    name: "MiniMax: MiniMax M2.1",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 204800,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'minimax/minimax-m2',
    name: "MiniMax: MiniMax M2",
    api: 'openai-chat',
    providerId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 204800,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
];
