// Model data. Sourced from https://openrouter.ai/api/v1/models (public,
// no key). OpenRouter is a no-auth model directory that proxies all the
// major Chinese vendors; we strip the upstream prefix and route through
// the provider's direct baseUrl. contextWindow / maxTokens / cost /
// modalities / reasoning flag all come from upstream metadata, which the
// direct endpoints honour identically.
import type { Model } from '../types.js';

export const qwenModels: Model<'openai-chat'>[] = [
  {
    id: 'qwen-2.5-72b-instruct',
    name: "Qwen2.5 72B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen-2.5-7b-instruct',
    name: "Qwen: Qwen2.5 7B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 29491,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen-2.5-coder-32b-instruct',
    name: "Qwen2.5 Coder 32B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 32768,
    maxTokens: 29491,
    cost: {
      input: 0.000001,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen-plus',
    name: "Qwen: Qwen-Plus",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 1000000,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen-plus-2025-07-28',
    name: "Qwen: Qwen Plus 0728",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 1000000,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen2.5-vl-72b-instruct',
    name: "Qwen: Qwen2.5 VL 72B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 128000,
    maxTokens: 115200,
    cost: {
      input: 0.000001,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-14b',
    name: "Qwen: Qwen3 14B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-235b-a22b',
    name: "Qwen: Qwen3 235B A22B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-235b-a22b-2507',
    name: "Qwen: Qwen3 235B A22B Instruct 2507",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-235b-a22b-thinking-2507',
    name: "Qwen: Qwen3 235B A22B Thinking 2507",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 117964,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-30b-a3b',
    name: "Qwen: Qwen3 30B A3B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-30b-a3b-instruct-2507',
    name: "Qwen: Qwen3 30B A3B Instruct 2507",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-30b-a3b-thinking-2507',
    name: "Qwen: Qwen3 30B A3B Thinking 2507",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 81920,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-32b',
    name: "Qwen: Qwen3 32B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-8b',
    name: "Qwen: Qwen3 8B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 131072,
    maxTokens: 8192,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-coder',
    name: "Qwen: Qwen3 Coder 480B A35B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-coder-30b-a3b-instruct',
    name: "Qwen: Qwen3 Coder 30B A3B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-coder-flash',
    name: "Qwen: Qwen3 Coder Flash",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-coder-next',
    name: "Qwen: Qwen3 Coder Next",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-coder-plus',
    name: "Qwen: Qwen3 Coder Plus",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0.000001,
    },
  },
  {
    id: 'qwen3-max',
    name: "Qwen: Qwen3 Max",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0.000001,
      output: 0.000004,
      cacheRead: 0,
      cacheWrite: 0.000001,
    },
  },
  {
    id: 'qwen3-max-thinking',
    name: "Qwen: Qwen3 Max Thinking",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0.000001,
      output: 0.000004,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-next-80b-a3b-instruct',
    name: "Qwen: Qwen3 Next 80B A3B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-next-80b-a3b-thinking',
    name: "Qwen: Qwen3 Next 80B A3B Thinking",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-235b-a22b-instruct',
    name: "Qwen: Qwen3 VL 235B A22B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-235b-a22b-thinking',
    name: "Qwen: Qwen3 VL 235B A22B Thinking",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 131072,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000004,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-30b-a3b-instruct',
    name: "Qwen: Qwen3 VL 30B A3B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-30b-a3b-thinking',
    name: "Qwen: Qwen3 VL 30B A3B Thinking",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-32b-instruct',
    name: "Qwen: Qwen3 VL 32B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 131072,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-8b-instruct',
    name: "Qwen: Qwen3 VL 8B Instruct",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: false,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3-vl-8b-thinking',
    name: "Qwen: Qwen3 VL 8B Thinking",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 131072,
    maxTokens: 32768,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-122b-a10b',
    name: "Qwen: Qwen3.5-122B-A10B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-27b',
    name: "Qwen: Qwen3.5-27B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-35b-a3b',
    name: "Qwen: Qwen3.5-35B-A3B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-397b-a17b',
    name: "Qwen: Qwen3.5 397B A17B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-9b',
    name: "Qwen: Qwen3.5-9B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-flash-02-23',
    name: "Qwen: Qwen3.5-Flash",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-plus-02-15',
    name: "Qwen: Qwen3.5 Plus 2026-02-15",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.5-plus-20260420',
    name: "Qwen: Qwen3.5 Plus 2026-04-20",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.6-27b',
    name: "Qwen: Qwen3.6 27B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.6-35b-a3b',
    name: "Qwen: Qwen3.6 35B A3B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 262144,
    maxTokens: 235929,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.6-flash',
    name: "Qwen: Qwen3.6 Flash",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.6-max-preview',
    name: "Qwen: Qwen3.6 Max Preview",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 262144,
    maxTokens: 65536,
    cost: {
      input: 0.000001,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0.000001,
    },
  },
  {
    id: 'qwen3.6-plus',
    name: "Qwen: Qwen3.6 Plus",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.7-flash',
    name: "Qwen: Qwen3.7 Flash",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 65536,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.7-max',
    name: "Qwen: Qwen3.7 Max",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0.000001,
      output: 0.000004,
      cacheRead: 0,
      cacheWrite: 0.000002,
    },
  },
  {
    id: 'qwen3.7-plus',
    name: "Qwen: Qwen3.7 Plus",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0.000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.8-2.4t-a95b',
    name: "Qwen: Qwen3.8 2.4T A95B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text'],
    contextWindow: 1048576,
    maxTokens: 131072,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.8-27b',
    name: "Qwen: Qwen3.8 27B",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.8-flash',
    name: "Qwen: Qwen3.8 Flash",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'qwen3.8-max',
    name: "Qwen: Qwen3.8 Max",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0.000003,
    },
  },
  {
    id: 'qwen3.8-max-0902',
    name: "Qwen: Qwen3.8 Max (0902)",
    api: 'openai-chat',
    providerId: 'qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 131072,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0.000003,
    },
  },
];
