// Model data. Sourced from https://openrouter.ai/api/v1/models (public,
// no key). OpenRouter is a no-auth cross-provider model directory whose
// `context_length` / `top_provider.max_completion_tokens` /
// `supported_parameters` / `architecture.input_modalities` mirror what the
// direct api.x.ai endpoint advertises, so the static
// list here matches what users actually get when they hit the baseUrl below.
import type { Model } from '../types.js';

export const xaiModels: Model<'anthropic'>[] = [
  {
    id: 'grok-4.6',
    name: "SpaceXAI: Grok 4.6",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 500000,
    maxTokens: 450000,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'grok-4.5',
    name: "SpaceXAI: Grok 4.5",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 500000,
    maxTokens: 450000,
    cost: {
      input: 0.000002,
      output: 0.000006,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'grok-4.3',
    name: "SpaceXAI: Grok 4.3",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 1000000,
    maxTokens: 900000,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'grok-4.20',
    name: "SpaceXAI: Grok 4.20",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 2000000,
    maxTokens: 1800000,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'grok-4.20-multi-agent',
    name: "SpaceXAI: Grok 4.20 Multi-Agent",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 2000000,
    maxTokens: 1800000,
    cost: {
      input: 0.000001,
      output: 0.000003,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: 'grok-build-0.1',
    name: "SpaceXAI: Grok Build 0.1",
    api: 'anthropic',
    providerId: 'x-ai',
    baseUrl: 'https://api.x.ai/v1',
    reasoning: true,
    input: ['text', 'image'],
    contextWindow: 256000,
    maxTokens: 230400,
    cost: {
      input: 0.000001,
      output: 0.000002,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
];
